### ISSUE TITLE
Send selected files with a normal form submit?

### ISSUE THREAD

**Issue by dalgard** [blueimp/jQuery-File-Upload#2637]
I have a special use case.

I would like to make use of some of the nice features of jQuery File Upload: client-side validation, drag'n'drop, multiple files, and previews (where supported) - but in the end I need to send the files to the server with a simple form submit.

The reason is that I need to support legacy CMS code on the server that simply loops the files in the post request.

Is this easily achievable?

**Comment by HoshiYamazaki** [comment]
`replaceFileInput` set to false, without overriden add method is not working, according to your answer here @blueimp
Probably some bug.

Also, if anybody needs to handle errors/success messages in form, I really recommend using bootbox.js and displaying messages by it. Really easy to implement ;)
