### ISSUE TITLE
Get image title and description in place of image name and size.

### ISSUE THREAD

**Issue by nishantsoni7** [blueimp/jQuery-File-Upload#2658]
I am using Jquery File Upload with additional data (image_title and image_description) to upload it to server.
The image and data is successfully uploaded to server but after uploading i want the image title and description to show instead of image name.

Through Firebug, i notice that all the data is sent correctly via post:

{"files":[{"name":"9f59f997c81f9714e124cf54ff346ed91381574739.jpg","size":17049,"type":"image\/jpeg","image_title":"title","image_description":"Description of image","url":"members_files\/test1\/portfolio\/9f59f997c81f9714e124cf54ff346ed91381574739.jpg","thumbnailUrl":"members_files\/test1\/portfolio\/thumbnail\/9f59f997c81f9714e124cf54ff346ed91381574739.jpg","deleteUrl":"http:\/\/localhost\/flinqo\/server\/php\/?file=9f59f997c81f9714e124cf54ff346ed91381574739.jpg","deleteType":"DELETE"}]}

but when i see the reponse after refreshing the page, i do not get the image title and description:

{"files":[{"name":"9f59f997c81f9714e124cf54ff346ed91381574739.jpg","size":17049,"url":"members_files\/test1\/portfolio\/9f59f997c81f9714e124cf54ff346ed91381574739.jpg","thumbnailUrl":"members_files\/test1\/portfolio\/thumbnail\/9f59f997c81f9714e124cf54ff346ed91381574739.jpg","deleteUrl":"http:\/\/localhost\/flinqo\/server\/php\/?file=9f59f997c81f9714e124cf54ff346ed91381574739.jpg","deleteType":"DELETE"}]} 

Please help me in getting the value from uploadHandler.php to shoe it to users.

Thanks in advance.

**Comment by ketanvault** [comment]
Hey hi. Have you solved this issue ?
