### ISSUE TITLE
Upload on Nginx not working

### ISSUE THREAD

**Issue by bazo** [blueimp/jQuery-File-Upload#2862]
hi

i'm using php with nginx, debian 7. when a file is uploaded the $_FILE array has all the info, no error and tmp_name is set to some value

but the file doesnt exist

i even tried changing upload_tmp_dir in php.ini because i thought it might have something to do with permissions but no go

am i missing something?

on my local IIS server everything works fine

**Comment by Mgrennes** [comment]
I've spend 1 day troubleshooting this.
These are the modification you should make to your NGINX configuration:
- events { } is missing
- Under the server config, you should have a root and an index
-  remove root html from lcation ~^... and ~ \.php

My root directory is /data/web

`events { }

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    gzip  on;
    gzip_disable 'msie6';
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

     server {
        listen       *:80;
        server_name  localhost;
        #define root when typing http://192.168.1.115
        root /data/web;
        index index.html index.php;

        location /data/web/ {
            root   html;
            autoindex on;
        }

        error_page  404              /404.html;
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

         # allow HTTP DELETE requests to the server/php/ directory:
        location /data/web/server/php {
            try_files $uri /data/web/server/php/index.php?$args;
        }

        # serve uploaded files statically, without executing any scripts:
        location ^~ /data/web/server/php/files {
            #root html;
            default_type application/octet-stream;
            types {
                image/gif     gif;
                image/jpeg    jpg;
                image/png    png;
            }
add_header X-Content-Type-Options 'nosniff';
            if ($request_filename ~ /(((?!\.(jpg)|(png)|(gif)$)[^/])+$)) {
                add_header Content-Disposition 'attachment; filename="$1"';
                # Add X-Content-Type-Options again, as using add_header in a new context
                # dismisses all previous add_header calls:
                add_header X-Content-Type-Options 'nosniff';
            }
        }

        location /files {
            root /data/web/server/php;
            internal;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        location ~ \.php$ {
            #root           html;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

        # deny access to .htaccess files
        location ~ /\.ht {
            deny  all;
        }

        # max upload size:
        client_max_body_size 5G;
    }

}
`
