### ISSUE TITLE
Vimeo Upload

### ISSUE THREAD

**Issue by floflock** [blueimp/jQuery-File-Upload#3160]
Hey there!

I need your uploader for uploading videos via vimeo API.
How can I do that?
It would be nice, if you can help me or prepare some Demo.

Thanks a lot!

**Comment by blueimp** [comment]
Really old issue, but back when I investigated the Vimeo Upload API, they didn't provide CORS headers, which would be a prerequisite for making this plugin work with their API.

In the email conversation with @floflock, he decided to do the Vimeo upload on server-side using the [official Vimeo PHP library](https://github.com/vimeo/vimeo.php).
