### ISSUE TITLE
Conflict with jquery.event.drop

### ISSUE THREAD

**Issue by lord-xeon** [blueimp/jQuery-File-Upload#3189]
I'm using [ThreeDubMedia's jquery.event.drop](http://threedubmedia.com/code/event/drop), and it seems to be causing an issue with jQuery-File-Upload.

The first time I make the fileupload widget it works fine.  After I destroy it and try and make a new one, I get an error that seems be caused in 

```
_initEventHandlers
```

jquery.event.drop makes the drop event global, and when `_initEventHandlers` adds the events, it goes into the jquery.event.drop event handler which is expecting different attributes.

Is there anyway to fix this, or am I doing something wrong?

**Comment by blueimp** [comment]
Revisiting this, the issue seems to be with the jquery.event.drop plugin making the drop event global.
Since this doesn't seem to be an issue created by this project, I'll close it.
