### ISSUE TITLE
Make UMD compatible

### ISSUE THREAD

**Issue by willdady** [blueimp/jQuery-File-Upload#3237]
Would be great if this library used a UMD wrapper so it was compatible with AMD and CommonJS style modules. My current use-case is I want to bundle this using Browserify (idealy without having to shim it).

At the very least, I think the current wrapper should not assume jQuery is available on the global object (window) by default. By changing `factory(window.jQuery);` to `factory(jQuery);` you at least give it a chance to walk the scope chain up to window, stopping if it finds jQuery somewhere in it's enclosing scope.

See: https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

**Comment by blueimp** [comment]
Not sure why I never closed this, but AMD style wrappers have been added long ago.
