### ISSUE TITLE
Problem parsing Exif data prior to upload

### ISSUE THREAD

**Issue by mjpalm21** [blueimp/jQuery-File-Upload#3246]
I am having a problem parsing Exif data prior to the file upload.

I have traced through jquery.fileupload-image.js and I can see that loadImage.parseMetaData is being called and that the exif and imageHead are added to the data object.

However when I try to call exif.getAll() in the send event it is not defined for the file object:

```
    send: function (e, data) {

            $.each(data.files, function (index, file) {
               // Get the EXIF data if it exists                   
               var exif = file.exif.getAll();
               _payloadData = processExif(exif,_payloadData);
            }); 

            return true;
```

Am I missing something?  How would exif.getAll() properly be called?

**Comment by ieraora** [comment]
Hi. I ask you what is the best way to send data.exif. I'm not very able with java, I asked to an expert in this field without success.
I need, for every image, to send these data with other fields, for example the name of gallery.

Thank you for reply.
