### ISSUE TITLE
Basic plus ui, RequireJS, Backbone Example

### ISSUE THREAD

**Issue by ikitx** [blueimp/jQuery-File-Upload#3277]
I use fews days to kick start the basic plus ui with requirejs and backbone but it still stucked. Please provide help. If there is any example to doing this that will be great.

**Comment by inspector71** [comment]
> 
> 
> I've marked this as feature request.
> 
> Please note that the Wiki is user editable

There's a link to a 404 in the Wiki that I thought I'd help fix. However from the web front end point of view, I'm not seeing the usual Github Edit button. as the Wiki actually been closed?

**Comment by blueimp** [comment]
The wiki used to be user editable, but I've disabled this feature after misuse.

Feel free to comment or mail me changes in the wiki you'd like to see and I will add them if appropriate.

**Comment by inspector71** [comment]
> The wiki used to be user editable, but I've disabled this feature after misuse.
> 
> Feel free to comment or mail me changes in the wiki you'd like to see and I will add them if appropriate.

Fair enough! I thought that might be the case re abuse. It's really kinda pathetic that GitHub does not have moderated wiki contributions. Wikipedia has had it for decades!

Would more than happily help you improve documentation if you can help me understand the code better sometimes. I don't want to be a hit-and-run user of open source and I really do appreciate this plugin immensely. Also appreciate you have limited time available though.

Just one thing I noticed, is there still a basic-plus example? It would appear not as this page 404s:

https://github.com/blueimp/jQuery-File-Upload/blob/master/basic-plus.html

... and I'm not seeing a file with that name in the release I downloaded.

Perhaps then the link to it should be removed from this page:

https://github.com/blueimp/jQuery-File-Upload/wiki/Plugin-files

https://i.imgur.com/nQuGRRU.png

If there is such an example page I'd love to see it :)

Perhaps we might best start a different Issue for documentation tweaks?

**Comment by blueimp** [comment]
Thanks for the heads-up, that wiki page actually had 16 dead links. 🙀 

The basic-plus example has been removed in this commit: 3142b42
The last tagged version that included it was [v9.34.0](https://github.com/blueimp/jQuery-File-Upload/tree/v9.34.0)

You might also benefit from this Wiki page:
https://github.com/blueimp/jQuery-File-Upload/wiki/Basic-plugin

**Comment by blueimp** [comment]
Looking that this feature request is from 2014 and the basic-plus version is not anymore supported, I'll close this issue.
