### ISSUE TITLE
Add event is called twice for drop file

### ISSUE THREAD

**Issue by janhartmann** [blueimp/jQuery-File-Upload#3340]
I am experiencing that my file is added two times when a file is dragged and dropped to my dropzone. If I manual select a file the file is only added once.

```
$(settings.fileInput, element).fileupload({
    url: pure.context + settings.url,
    type: settings.type,
    dropZone: $(settings.dropZone, element),
    add: function (e, data) {
        console.log(e);
    },
    progress: _updateProgress,
    done: function (e, data) {
        //alert(data.result);
    },
    fail: function (e, data) {
        alert(data.textStatus);
    }
});
```

My console tells me its the same event that is called:

![dgfdfg](https://cloud.githubusercontent.com/assets/1107383/4161265/1106c484-34cb-11e4-8778-3a7c963a3221.PNG)

Anyone have a clue on why?

**Comment by OllieStrevel** [comment]
Hello @janhartmann, did you archieve fix this?
