### ISSUE TITLE
Chunked upload to S3 not working

### ISSUE THREAD

**Issue by martinbean** [blueimp/jQuery-File-Upload#3353]
I’m trying to use this plugin to upload large files (videos) to an S3 bucket in chunks. I have this code:

``` js
$('.form-upload').fileupload({
    maxChunkSize: 100000000
});

$('.form-upload').bind('fileuploadadd', function(e, data) {
    $.ajax({
        async: false,
        data: {
            name: data.files[0].name
        },
        dataType: 'json',
        success: function(response) {
            if (response.video) {
                // Creates a record in my database and returns its details
                data.submit();
            }
        },
        type: 'POST',
        url: '/video'
    });
});
```

I select a file and the upload appears to work. The right events are fired, and it takes the right amount of time to upload the file I’m testing with (~700MB) on the connection I’m on.

However, after the upload finished, when I go to the AWS Console to view my file in the S3 bucket it has a file size of ~70MB and is un-playable; it’s as though the chunks are being re-assembled properly on the AWS side.

Have I done anything wrong in my HTML form implementation above?

**Comment by Mayank-savaliya** [comment]
@martinbean were you able to solve it? If yes could you please share how you did it

**Comment by martinbean** [comment]
@Mayank-savaliya This issue is 7-and-a-half years ago. I can barely remember the code I wrote 7-and-a-half _months_ ago…

I’ve done lots of AWS uploading since and just use Amazon’s JS SDK directly and don’t have any issues: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-example-photo-album.html
