### ISSUE TITLE
UploadHandler.php in line 341-353 get_config_bytes($val)

### ISSUE THREAD

**Issue by gorkemkara16** [blueimp/jQuery-File-Upload#3531]
Hello because a correct value has not been assigned
I was getting an error on line 348 in the UploadHandler.php file. I solved this problem and wanted to write the solution for those who encountered the error.

```
  function get_config_bytes ($ val) {
         $ val = trim ($ val);
         $ last = strtolower ($ val [strlen ($ val) -1]);
         $ val = intval ($ val); // fixes when intval () is added here
         switch ($ last) {
             case 'g':
                 $ val * = 1024;
             case 'm':
                 $ val * = 1024;
             case 'k':
                 $ val * = 1024;
         }
         return $ this-> fix_integer_overflow ($ val);
     }
```

The correction should be considered.
Good work for everyone.

**Comment by blueimp** [comment]
It seems that you're using an old version of this library, the latest version of the `get_config_bytes` functions looks like this, which also fixes your issue:

```php
    public function get_config_bytes($val) {
        $val = trim($val);
        $last = strtolower($val[strlen($val)-1]);
        if (is_numeric($val)) {
            $val = (int)$val;
        } else {
            $val = (int)substr($val, 0, -1);
        }
        switch ($last) {
            case 'g':
                $val *= 1024;
            case 'm':
                $val *= 1024;
            case 'k':
                $val *= 1024;
        }
        return $this->fix_integer_overflow($val);
    }
```

**Comment by thelukscolor** [comment]
function get_config_bytes($val) {
        $val = trim($val);
        $last = substr($val, -1);
        $val  = rtrim($val, $last);
        switch(strtolower($last)) {
            case 'g':
                $val *= 1024;
            case 'm':
                $val *= 1024;
            case 'k':
                $val *= 1024;
        }
        return $this->fix_integer_overflow($val);
    }
