### ISSUE TITLE
jQuery chain error in  jquery.iframe-transport.js

### ISSUE THREAD

**Issue by threecups** [blueimp/jQuery-File-Upload#3532]
Base on jquery 1.12.4,  changing this(in line 125-127):
`$('<input type="hidden"/>').prop('name', field.name).val(field.value).appendTo(form);`

into:
`$('<input type="hidden"/>').prop('name', field.name).appendTo(form).val(field.value);`

**Comment by chucklu** [comment]
https://github.com/blueimp/jQuery-File-Upload/blob/master/package.json#L38
You should upgrade the jquery library.

**Comment by blueimp** [comment]
@threecups could you provide a minimal example to reproduce the chaining error, e.g. on codepen or jsfiddle?

@chucklu this has come up in the past, but that modifier is a minimal version and there is no strong reason to require a higher version.

**Comment by threecups** [comment]
@blueimp That is my fault, NOT YOU.  
I lost the context, when i overwrite jquery function 'val', and that broken the jquery chaining, eg: console.log($('input').val('balabala'));  // will be console 'null'

**Comment by blueimp** [comment]
Alright, as far as I understand your comment we can close this issue then.
Thanks for clearing that up!
