### ISSUE TITLE
Q: how to in an progress event identify one out of several parallel uploading files

### ISSUE THREAD

**Issue by th-s-op** [blueimp/jQuery-File-Upload#3533]
Hi,

I am implementing a simple Ajax upload with "mutltiple" enabled and I want to use the "progress" event to show the progress in % for all files currently uploading in parallel. I wonder how when I get the progress event called, I can identify exactly for which file it is.
In theory, I would use the data.files[].name property, but I wonder if this could break if someone was uploading a file with the same name in parallel. I feel like using some "ID" would be safer - is there any?

Thanks a lot for this great piece of software!

**Comment by blueimp** [comment]
Hi @th-s-op,

there are multiple ways to approach this, the following is the one I’ve used:

In the sample UI library, the rendered element for each individual file upload is saved as context property in the data object, which is the second argument to most of the callbacks:
https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-ui.js#L100

This allows to reference the same rendered element in the progress callback:
https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-ui.js#L280

And yes, the file name is not a safe identifier as it’s definitely possible to upload files with the same name, e.g. by selecting the same file multiple times or by selecting files with the same name from multiple folders.

Hope that helps!

**Comment by th-s-op** [comment]
Thanks a lot - that pointed me to the right direction. I changed this approach a little bit: in the "change" event handler, I am counting up a global "fileID" variable and put this number into the corresponding data.file[].context which I retrieve later on in the "progress" event handler.
