### ISSUE TITLE
Server-Side platform (NodeJS Express)

### ISSUE THREAD

**Issue by LoYungSum** [blueimp/jQuery-File-Upload#3535]
As the title said, is there an example of how to accept the file upload request in nodejs (express)?

**Comment by LoYungSum** [comment]
Edit: Which is useable

**Comment by blueimp** [comment]
An _unmaintained_ pure Node.js implementation can be found until the commit [f35e807a5dd17a5fea20952238a75c1991065c30](https://github.com/blueimp/jQuery-File-Upload/tree/f35e807a5dd17a5fea20952238a75c1991065c30) under the [server/node](https://github.com/blueimp/jQuery-File-Upload/tree/f35e807a5dd17a5fea20952238a75c1991065c30/server/node) folder.

It doesn't use Express, but implements the [http.createServer requestListener interface](https://nodejs.org/api/http.html#http_http_createserver_options_requestlistener).

See also the [Demo-implementation](https://github.com/blueimp/jQuery-File-Upload/wiki/Demo-implementation) wiki.

There are also a number of 3rd-party implementations listed on the Wiki, including middleware for ExpressJS:
https://github.com/blueimp/jQuery-File-Upload/wiki#javascript
