### ISSUE TITLE
boostrap 4 template fade in issue

### ISSUE THREAD

**Issue by SalehGladius** [blueimp/jQuery-File-Upload#3537]
bootstrap 4 uses `show` css class to display elements, instead of `in` class.

when you fix this issue?

**Comment by titulebolide** [comment]
Meanwhile there is a simple fix for those who are looking for one : [https://stackoverflow.com/questions/42249722/how-to-update-blueimp-jquery-file-upload-to-use-bootstrap-4#48162651](https://stackoverflow.com/questions/42249722/how-to-update-blueimp-jquery-file-upload-to-use-bootstrap-4#48162651)

**Comment by blueimp** [comment]
Thanks for the report @SalehGladius and thanks for providing an alternative solution @titulebolide.

The latest version of blueimp-file-upload (`10.4.0`) now provides a `showElementClass` option that can be set to `show` for use with Bootstrap 4.
