### ISSUE TITLE
Minimum number of files to upload?

### ISSUE THREAD

**Issue by vladav** [blueimp/jQuery-File-Upload#3539]
Hi,

How can I change the code to force minimum number of files to be uploaded? How can I add validation for minimum number of files?

Regards,
Vladimir

**Comment by blueimp** [comment]
Hi Vladimir,

I think preventing the user to upload a single file unless they select the minimum number is neither user-friendly nor enforceable, as the user can cancel the requests for any files or even cancel a request partway through.

A minimum number of files is better implemented by displaying a message asking the user to upload more files until that minimum is reached.
You could make the next step in your user flow available as soon as the required number of files are available on server-side.

To check if the user has uploaded the number of required files could be done with the following code in the sample UI:

```js
$('#fileupload').bind('fileuploadcompleted', function (e, data) {
  if ($('.files .template-download').length >= MIN_NUMBER_OF_FILES) {
    // User uploaded required number of files
  }
})
```

**Comment by blueimp** [comment]
Since there were no more comments, I’m closing this as resolved.
