### ISSUE TITLE
Issue with is_valid_image_file()?

### ISSUE THREAD

**Issue by Insomnia88** [blueimp/jQuery-File-Upload#3547]
I don't receive any error at uploading when my files are too small for example (current build). The server is running on PHP 7.2.5. The reason for the missing errors seems to be the `is_valid_image_file()` function. I use an older build of the file on another server where it works like it should.

At line 437
```
if (($max_width || $max_height || $min_width || $min_height)
            && $this->is_valid_image_file($uploaded_file)) {
```

the same part in an older build
```
if (($max_width || $max_height || $min_width || $min_height)
           && preg_match($this->options['image_file_types'], $file->name)) {
```

Maybe it has something to do with the server but I wonder how. When I echo the `$uploaded_file` the first time I receive a part/file of my servers `/tmp/` directory.

**Comment by blueimp** [comment]
Thanks for the report @Insomnia88.
I can confirm this as a regression and have pushed a refactored version that should resolve the issue.
