### ISSUE TITLE
Multiple file upload over https hangs

### ISSUE THREAD

**Issue by senolkulbay** [blueimp/jQuery-File-Upload#3548]
I've downloaded the master files and run the demo on IIS 8.5 and IIS 10.0. Everything is working fine on http. If I try to upload multiple files on https the upload progress (overall progress bar and every single file's progress bar) hangs after a while (After ~2MB total upload). The upload progress goes on with long delays. 5 files (Total ~4 MB) take 7 mins to upload.

maxAllowedContentLength and maxRequestLength values are set as max on IIS. I couldn't find out what the problem is.

**Comment by senolkulbay** [comment]
I found what the problem is. It's about HTTP/2 Protocol. I had to disable it. Then worked fine.
You can try it with `chrome --disable-http2`

**Comment by blueimp** [comment]
Thanks for the report @senolkulbay.
This sounds more like an issue with IIS and not with this project, as this is not reproducible for me on the demo or the provided Docker environment.
I'll close this for now, but feel free to comment if you believe this assessment is incorrect.
