### ISSUE TITLE
Client side resizing stop working (Chrome)

### ISSUE THREAD

**Issue by marceloagil** [blueimp/jQuery-File-Upload#3549]
Hi there.

We have been using Jquery File Upload for 2 years now. We didn't changed anything in our project and this week, customers have told us that upload was not working.

So, after a few tests, I'v found the problem: Jquery File Upload stop resizing at client side. No output error, nothing. Than he outputs an error saying that file size is bigger than allowed in php.ini.

We use jquery-11.0. and blue-imp-file-upload 9.24.1

The file we upload is about 6 mbs size.

Anyone with same problem?

Here is the entire code that deals with upload:

`
$(function() {
        var filenames = '';
        'use strict';
        document.getElementById("carregando").style.display = 'none';
        var url = '<?php echo base_url(); ?>uploads/do_upload/<? echo $this->uri->segment(3); ?>/<? echo $this->uri->segment(1); ?>',
            uploadButton = $('<button/>')
            .addClass('btn btn-primary')
            .prop('disabled', true)
            .text('Processando...')

            .on('click', function() {
                var $this = $(this),
                    data = $this.data();
                $this
                    .off('click')
                    .text('Abort')
                    .on('click', function() {
                        $this.remove();
                        data.abort();
                    });
                data.submit().always(function() {
                    $this.remove();
                });
            });
        var filestoupload = 0;
        $('#fileupload').bind('fileuploadadd', function(e, data) {
            filestoupload++;
        });
        $('#fileupload').fileupload({
                url: url,
                dataType: 'json',
                paramName: 'files[]',
                autoUpload: true,
                acceptFileTypes: /(\.|\/)(gif|jpe?g)$/i,
                maxFileSize: 100000000,
                imageForceResize: true,
                // Enable image resizing, except for Android and Opera,
                // which actually support image resizing, but fail to
                // send Blob objects via XHR requests:
                disableImageResize: /Android(?!.*Chrome)|Opera/
                    .test(window.navigator.userAgent),
                //previewMaxWidth: 100,
                //previewMaxHeight: 100,
                imageMaxWidth: 10000,
                imageMaxHeight: 10000,
                imageCrop: false,
                previewCrop: true,
                sequentialUploads: true,
                imageOrientation: true,
            }).on('fileuploadadd', function(e, data) {
                data.context = $('<div/>').appendTo('#files');
                $('#progress .progress-bar').css(
                    'width',
                    "0" + '%'
                );
                $.each(data.files, function(index, file) {
                    var node = $('<p/>')
                        .append($('<span/>').text(file.name));
                    if (!index) {
                        node
                            .append('<br>')
                            .append(uploadButton.clone(true).data(data));

                    }
                    node.appendTo(data.context);
                });
            }).on('fileuploadprocessalways', function(e, data) {
                var index = data.index,
                    file = data.files[index],
                    node = $(data.context.children()[index]);
                if (file.preview) {
                    node
                        .prepend('<br>')
                        .prepend(file.preview);
                }
                if (file.error) {
                    node
                        .append('<br>')
                        .append($('<span class="text-danger"/>').text(file.error));
                }
                if (index + 1 === data.files.length) {
                    data.context.find('button')
                        //.text('Iniciar upload')
                        .text('Processando...') //o upload vai ser automágico :D
                        .prop('disabled', !!data.files.error);

                }
            }).on('fileuploaddone', function(e, data) {
                $.each(data.result.files, function(index, file) {
                    if (file.url) {
                        filenames = filenames + data.result.files[0].name + ',';
                        data.context.find('button')
                            .text('Enviada p/ processamento');
                        //.remove();
                    } else if (file.error) {
                        var error = $('<span class="text-danger"/>').text(file.error);
                        $(data.context.children()[index])
                            .append('<br>')
                            .append(error);
                    }
                });
                var activeUploads = $('#fileupload').fileupload('active');
                /*if(activeUploads == 1) {
                    console.info("All uploads done");
                    var filestoupload2 = 'IM_NUMERO_FOTOS + '+filestoupload;
                    ajax_altera_silencioso("IMOVEIS","IM","<? echo $codigo; ?>","IM_NUMERO_FOTOS", filestoupload2);
                    sendToSpace(filenames,<? echo $codigo; ?>,'property',1);

                    filenames = '';
                    filestoupload = 0;
                }*/
            }).on('fileuploadprogressall', function(e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);
                $('#progress .progress-bar').css(
                    'width',
                    progress + '%'
                );
                $('#progress_percentage').html(progress + ' %');
                if (progress >= 100) {
                    $('#progress').removeClass('active');
                    $('#progress_percentage').html('Enviando para a nuvem...');
                }
            }).on('fileuploadfail', function(e, data) {
                $.each(data.files, function(index) {
                    var error = $('<span class="text-danger"/>').text('Ocorreu um erro: ' + $(data.jqXHR.responseText).filter("title").text());
                    $(data.context.children()[index])
                        .append('<br>')
                        .append(error);
                    return false;
                });
            }).prop('disabled', !$.support.fileInput)
            .parent().addClass($.support.fileInput ? undefined : 'disabled');

        $('#fileupload').on('fileuploaddone', function(e, data) {
            var activeUploads = $('#fileupload').fileupload('active');
            if (activeUploads == 1) {
                console.info("All uploads done");
                var filestoupload2 = 'IM_NUMERO_FOTOS + ' + filestoupload;
                ajax_altera_silencioso("IMOVEIS", "IM", "<? echo $codigo; ?>", "IM_NUMERO_FOTOS", filestoupload2);
                console.log('Filenames: ' + filenames);
                sendToSpace(filenames, <? echo $codigo; ?>, 'property', 1);

                filenames = '';
                filestoupload = 0;
            }
        });
    });
`

**Comment by marceloagil** [comment]
Removing this did the trick:

maxFileSize: 100000000,
            imageForceResize: true,
            imageMaxWidth: 10000,
            imageMaxHeight: 10000,

**Comment by marceloagil** [comment]
Reopening issue.

Reason: files above 6mbs are resized. Files with 11mbs are not getting resized. Something happens (without errors in console).

How to make possible resize large files in the version I'm using?

**Comment by blueimp** [comment]
`loadImageMaxFileSize` is the option that limits the size of files to load for image processing, it defaults to 10MB:
https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-image.js#L121
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#loadimagemaxfilesize

**Comment by danforestview** [comment]
I have the same issue using the UploadHandler.php file. Cannot resize images larger than 1.1M.
No errors are coming up. Everything else is working fine.

Server memorylimit = 120M 

Tried 'convert_params' => '-limit memory 120MiB -limit map 120MiB',

Thanks

**Comment by kazi-shahin** [comment]
In my case more than 10 MB sized image getting error for generating preview. And as followed failed not upload. Any thoughts ?
