### ISSUE TITLE
Template engine demo not working.

### ISSUE THREAD

**Issue by Serpent6877** [blueimp/jQuery-File-Upload#3551]
Using the base demo code I attempted to use the template override on the template page https://github.com/blueimp/jQuery-File-Upload/wiki/Template-Engine but doesn't seem to work. No errors, no data.

**Comment by blueimp** [comment]
Thanks for the report - I've removed the unnecessary `filesContainer` option from the wiki page, which pointed to `table.files`, which is an element that doesn't exist in the current demo HTML.

The example should now work again (at least it did in my test with the latest demo).
