### ISSUE TITLE
Upload images for different categories for one user

### ISSUE THREAD

**Issue by devintegrated** [blueimp/jQuery-File-Upload#3554]
I am using the jQuery File Upload plugin to upload images per categories for each of my users. Each user may upload different images for different categories that they are enabled for. However, the  plugin creates a session that shows the same images for all categories. For example if I upload 5 images under Clothes category, when I go to Shoes category the same images are displayed there when actually I've not uploaded any images there. Is there a way to separate the uploads for each categories? I've checked the wiki tab but there's nothing there to help in this regard. I tried to create a session for each category but I'm getting server side error.

FYI: I'm using the demo example  and PHP for server side, I'm also using the mysql db integration.

I tried to set further conditions to retrieve images by category ID from db and display that, but it's not working since the displayed uploaded images are not retrieved from DB.

Your help will be greatly appreciated.

Thank you.

**Comment by blueimp** [comment]
Please see #2190
