### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Bich87** [blueimp/jQuery-File-Upload#3555]
Hello, I try to use this basic plugin with

PHP 7
jQuery 3.3.1
Google Chrome

When I try to upload some files, the console says 403 forbidden. The directory I'm using works fine with "summernote WYSIWYG" plugin.

Needing help please..

:)

**Comment by blueimp** [comment]
Hi @Bich87 

You might have to configure your server (Apache? Nginx?) to allow larger upload sizes, but it could also be a different configuration problem. [Status code 403](https://en.wikipedia.org/wiki/HTTP_403) means "Forbidden", so with your current setup, file uploads in general or file uploads larger than a given size might not be allowed.

Please also see #2190
