### ISSUE TITLE
multipart upload to bypass 5gb upload limit

### ISSUE THREAD

**Issue by masudhossain** [blueimp/jQuery-File-Upload#3567]
Having an issue where uploading 5gb isn't working, and found out i need to upload as multipart. How would I do this here? I am directly uploading to digital ocean spaces with aws_s3 gem

**Comment by blueimp** [comment]
Please have a look here:
https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads

Please also refer to #2190
