### ISSUE TITLE
[docs] Extended-progress-information

### ISSUE THREAD

**Issue by inspector71** [blueimp/jQuery-File-Upload#3607]
https://github.com/blueimp/jQuery-File-Upload/wiki/Extended-progress-information

This page looks like it could use some clarity.

Questions:

1. Does "the UI version" refer to the jQuery UI library or https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-ui.js ? I suspect the latter :)
2. Does jQuery-File-Upload (JFU) still support all of the extended progress information - formatted speed, time remaining, uploaded / total and uploaded / percentage - or just `bitrate` and if so, what are the variable names? (I've tried to interrogate `data` values but only see `loaded`, `total` and `bitrate` either at the top level of within `_progress` )

Hope this helps (more than the ... "not work !!" issue). Do not want to create stress for @blueimp

**Comment by blueimp** [comment]
Thanks for the heads up, I've updated the documentation for clarity.
Please let me know if this helps.

**Comment by inspector71** [comment]
Woohoo, definite improvement for sure!

From my PoV perhaps the only lack of clarity now is _how_ the UI version displays this data. If I'm understanding things correctly, the UI version is the basis for the demo page ... but until I just checked this now, I had not seen that demo working. Now I have, I can visualise what the UI version does.

I think this possible highlights a broader theme the documentation could be adjusted to address. That is, there appears to often be an assumption the reader has the default, OOTB version / instance of JFU (jQuery-File-Upload) in their mind's eye when they start reading. The documentation then goes on to explain the manual / custom / hand-coded or just alternative way to implement the same thing. The latter is brilliant. Very helpful for those who do not want to just drop the default in and hope it works. However if there's a picture of the former to summarise the default, that would help the reader to orient themselves with the A / B flow of the documentation style. A bit like this:

(A) JFU does X feature since the Y version, viewable in the Z demo.

(B) But if you want to rig things up yourself a bit differently, here's A, B and C cool code tips and references to help get you started.

If (A) included a literal visual reference to illustrate the contrast of A vs B, the reader may not get stuck at A wondering why they possibly feel disoriented :) 

Perhaps a screenshot of JFU in action, showing these specific features?

Hope I've not gone too broad on this. I'm familiar with writing documentation whilst your headspace is deep embedded into the code. It's not always easy to extract yourself and write the documentation from a new user's perspective. That and some eejoits apparently butchered your documentation which is just petty vandalism and unreasonable lowlife behaviour!

**Comment by blueimp** [comment]
Thanks for the suggestions @inspector71, I definitely appreciate it.

I'm actually quite fond of the art of writing good documentation and like projects that have
- a getting started guide
- how-to articles
- a reference documentation
- use a good amount of example code (ideally executable in an online code editor)
- use supporting media (screenshots, videos where appropriate, etc.).

That being said, jQuery File Upload is old software (not state of the art of front-end development anymore) and while I'll continue to maintain it in the foreseeable future, I don't want to invest much time in it. Which means I likely won't change much about the existing documentation.

By the way, the Wiki is actually itself a Git repo that can be cloned with the following URL:
https://github.com/blueimp/jQuery-File-Upload.wiki.git
Unfortunately, GitHub doesn't provide its pull request interface for it.

**Comment by inspector71** [comment]
Yeah, GitHub's wiki effort leaves a lot to be desired. In fact, it's
amateurish.

Regarding 'old software' though, I feel there's a myth in software that old
equals outdated and bad.

This plugin works. It's good value. Unless there's something equally as
functional (rarely does one project implement feature parity for a project
it is trying to improve upon) and better, I see no reason to kill off old
software simply based on age. 'state of the art' is just as often a
euphemism for untested, unproven. JFU has stood the test of time.

What do you think is outdated about the code?

**Comment by blueimp** [comment]
jQuery File Upload definitely still has good use cases, e.g. for projects that need good backwards-compatible browser support, which is also true for jQuery in general.

But if you want to implement a full application in the browser, there are better choices than jQuery, e.g. React, which basically became the standard for front-end development and allows you to reuse the same code for server-side and client-side rendering.

I don't think that old software is necessarily worse than new software, but there are also advancements in technology that make certain pieces of software obsolete.
e.g. modern browsers come with new and improved APIs that make the majority of what jQuery offered obsolete, so you can implement the same features with less code and better performance.

Modern browsers don't yet offer a dedicated file upload widget, but you can get there with less code than what was required and is included in jQuery File Upload.

But I also agree with you, jQuery File Upload can still be useful and I'm not abandoning it.
I'm just minimizing my maintenance effort. :)

**Comment by blueimp** [comment]
Closing this, since the original issue has been solved.
