### ISSUE TITLE
Can't upload files, server expecting a user

### ISSUE THREAD

**Issue by Mgrennes** [blueimp/jQuery-File-Upload#3619]
Hi,

I tried not post here, but I don't know where to ask. I've got jQuery file upload + TOMCAT + php java bridge running. On top of that, I have SPRING security running that authenticates users via active directory.

If I try to upload a file, i'll get a 403 forbidden error.

If I touch a file in the directory /server/php/files and access http://localhost:8080/uploader/server/php/index.php I'll get this in return:

{"files":[{"name":"doge.png","size":18709,"url":"http:\/\/bob@192.168.1.115:8080\/uploader\/server\/php\/files\/doge.png","deleteUrl":"http:\/\/bob@192.168.1.115:8080\/uploader\/server\/php\/index.php?file=doge.png","deleteType":"DELETE","deleteWithCredentials":true}]}

I'm guessing this is because the request, when sent to the server, doesn't include bob@ in front of the full URL.

Inspecting the header reponse from the website, I can see that I have what is required for this to work:
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials

What am I doing wrong?

Thanks for helping!

**Comment by blueimp** [comment]
Hello @Mgrennes,

A `GET` request to the PHP demo returns a JSON array of the existing files, which is what you're seeing when you're accessing http://localhost:8080/uploader/server/php/index.php.

Regarding your JAVA Spring setup I can't provide support, but you might find help on StackOverflow.
(see also https://github.com/blueimp/jQuery-File-Upload#support)

Since this is not an issue in the project itself, I'll close it, but feel free to provide more information here, as these posts still provide help for other users as well.

**Comment by Mgrennes** [comment]
Hi Blueimp, I was mostly interessted to see why I had bob@localhost in front of my URL and how your application was dealing with authenticated users uploaded files. I'll make sure to check out stackoverflow. Thanks for this application and your support! :)

**Comment by blueimp** [comment]
I see. You can see how the absolute URL is constructed on server-side in PHP here in the function `get_full_url`:
https://github.com/blueimp/jQuery-File-Upload/blob/master/server/php/UploadHandler.php#L224
It looks like for some reason `$_SERVER['REMOTE_USER']` is not empty in your case.

**Comment by Mgrennes** [comment]
That's it. It's not empty because SPRING has the user authenticate against AD first, before presenting your jQuery file upload. Thank you I appreciate :)

**Comment by Mgrennes** [comment]
I think what I'm trying to do is not doable. TOMCAT + SPRING + jQuery file upload.
I think i'll have to settle with NGINX + some sort of AD auth plugin + jQuery File upload.
Many thanks for your help!
