### ISSUE TITLE
Google Storage + Signed URLs + Django 

### ISSUE THREAD

**Issue by UtkuBulkan** [blueimp/jQuery-File-Upload#3621]
I have the following js code and it uses the signed-url api to get signed urls for uploading content to google storage via Django api.

When I use it with the following code :

```
xhr.open("PUT", data.signed_url);
xhr.setRequestHeader('Content-Type', file.type);
xhr.send(file);
```

It works fine and I am able to upload to Google Storage very large files. But obviously, when I do that, I cannot use any progress-bar features of jquery-file-upload.

Can you please suggest on how I should alter the data.submit(), where shall I put it, and how should I change the options or settings prior to submitting. Should I be overriding add or submit callback ?

I feel that there is a missing support for Google Storage with Jquery-file-upload as the only example covers only obsolute  Google Blobstore in the following link : [https://github.com/blueimp/jQuery-File-Upload/wiki/Google-App-Engine](url)

```
$("#fileupload").fileupload({
    dataType: 'json',
    type: 'PUT',
    sequentialUploads: true,

    submit: function(e, data) {
        var $this = $(this);
        $.each(data.files, function(index, file) {
            // pack our data to get signature url
            var formData = new FormData();
            formData.append('filename', file.name);
            formData.append('type', file.type);
            formData.append('size', file.size);

            // Step 3: get our signature URL
            $.ajax({
                url:  '/api/getsignedurl/',
                type: 'POST',
                processData: false,
                contentType: false,
                dataType: 'json',
                headers: {
                    'X-CSRFToken': Cookies.get('csrftoken'),
                },
                primary_data: data,
                data: formData
            }).done(function (data) {
                // Step 5: got our url, push to GCS
                const xhr = new XMLHttpRequest();
                if ('withCredentials' in xhr) {
                    console.log("With credentials");
                    xhr.open("PUT", data.signed_url, true);
                }
                else if (typeof XDomainRequest !== 'undefined') {
                    console.log("With domainrequest");
                    xhr = new XDomainRequest();
                    xhr.open("PUT", data.signed_url);
                }
                else {
                    console.log("With null");
                    xhr = null;
                }

                //What shall I do to make the following work for uploading GS
                this.primary_data.url = data.signed_url;
                this.primary_data.headers={'Content-Type': file.type};
                this.primary_data.submit();

                xhr.onload = () => {
                    const status = xhr.status;
                    if (status === 200) {

                    } else {
                        alert("Failed to upload 1: " + status);
                    }
                };

                xhr.onerror = () => {
                    alert("Failed to upload 2");
                };
                //When the code below uncommented, it uploads to GS succesfully.
                //xhr.setRequestHeader('Content-Type', file.type);
                //xhr.send(file);
            });
        });
    },
```

**Comment by blueimp** [comment]
You've already set the `type:'PUT'`, but you also need to set `multipart:false`, so jQuery File Upload sends each file as is without wrapping them in `multipart-form-data`:
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#multipart

In your submit handler, after retrieving the signed URL, you then set `data.url = signedURL` and use the File Upload send API method to submit the files, see:
https://github.com/blueimp/jQuery-File-Upload/wiki/Submit-files-asynchronously#using-the-submit-callback-option

**Comment by UtkuBulkan** [comment]
Thanks for your detailed and fast support, now I am able to upload the content. Previously my implementation was uploading to Google Storage following this path :

Browser -> Django Backend -> Google Storage

Since I have implemented signed_url method with your help, now it uploads directly from Browser to Google Storage (and getting signed_url from Django Backend)

However since I started using this, Browser stopped informing Django Backend regarding the upload finished (done) information and provides the following log due to csrf mismatch : 

```
[04/Apr/2020 09:27:37] "POST /api/getsignedurl/ HTTP/1.1" 200 657
Forbidden (CSRF token missing or incorrect.): /videos/browse/
[04/Apr/2020 09:27:38] "PUT /videos/browse/ HTTP/1.1" 403 2513
```

I feel like now the browser is trying to use  the csrf token that is uses to communicate to Google Storage to upload the content, which obviously the actual backend refuses.

Here below you can find my html code as well.

```
  <div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-videos">
      <span class="glyphicon glyphicon-cloud-upload"></span> Upload videos
    </button>
    {% csrf_token %}
    <input id="fileupload" type="file" name="file" multiple
           style="display: none;"
           data-url="{% url 'videos:browse' %}"
           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
  </div>
```

It might not be exactly relevant to jQuery-File-Upload, yet it is slightly connected. Can I kindly ask if you would be able to comment on this, what should be the strategy in here ?

**Comment by blueimp** [comment]
Since the original question has been answered and it's not an issue with jQuery File Upload, I'll close this.
Feel free to comment your solution on this ticket for others to find though!

**Comment by UtkuBulkan** [comment]
Thanks for the guidance, 

The solution that I have followed to inform backend for a successful upload  is the following :

```
urlpatterns = [
    path('upload/signedurl/', FileUploadSignedURL.as_view()),
    path('upload/success/', FileUploadSuccess.as_view()),
}
```

An api to receive signed-url from backend and following that another api to inform the backend that browser has successfully uploaded to Google Storage.
