### ISSUE TITLE
codeigniter  don't change filename in    'replace_dots_in_filenames' => $newfilename

### ISSUE THREAD

**Issue by mdjamilaj** [blueimp/jQuery-File-Upload#3622]
i have try to change codeigniter  filename and new name store in database but codeigniter  don't work in file name replace options and i dont find image before change and don't find ext (.png/.jpg)

**Comment by blueimp** [comment]
Hi @mdjamilaj, please see #2190

**Comment by mdjamilaj** [comment]
i use blueimp/jQuery-File-Upload in codeignetor to upload multiple file and same time i have save file path in database to change filename a unique name for example  time() or id but i have try to change filename to 'replace_dots_in_filenames' options but name not changed and insert before i don't find filename or ext  .. if i don't find filename so how to insert filename in database and replace  filename
