### ISSUE TITLE
Make an alternative example without using "Javascript-Template"

### ISSUE THREAD

**Issue by oliverbob** [blueimp/jQuery-File-Upload#3628]
Hi Sebastian Tschan or any contributor for that matter,

The Javascript Template you have provided in the example confuses an unfamiliar developer trying to make a quick solution to add your library to existing code built on PHP and jQuery.

Can you provide the same example you have provided for plain jQuery syntax without seemingly forcing developers to learn your javascript template library?

Or how can I convert the following code into jQuery?

```
<script id="template-upload" type="text/x-tmpl">
      {% for (var i=0, file; file=o.files[i]; i++) { %}
          <tr class="template-upload fade">
              <td>
                  <span class="preview"></span>
              </td>
              <td>
                  {% if (window.innerWidth > 480 || !o.options.loadImageFileTypes.test(file.type)) { %}
                      <p class="name">{%=file.name%}</p>
                  {% } %}
                  <strong class="error text-danger"></strong>
              </td>
              <td>
                  <p class="size">Processing...</p>
                  <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
              </td>
              <td>
                  {% if (!o.options.autoUpload && o.options.edit && o.options.loadImageFileTypes.test(file.type)) { %}
                    <button class="btn btn-success edit" data-index="{%=i%}" disabled>
                        <i class="glyphicon glyphicon-edit"></i>
                        <span>Edit</span>
                    </button>
                  {% } %}
                  {% if (!i && !o.options.autoUpload) { %}
                      <button class="btn btn-primary start" disabled>
                          <i class="glyphicon glyphicon-upload"></i>
                          <span>Start</span>
                      </button>
                  {% } %}
                  {% if (!i) { %}
                      <button class="btn btn-warning cancel">
                          <i class="glyphicon glyphicon-ban-circle"></i>
                          <span>Cancel</span>
                      </button>
                  {% } %}
              </td>
          </tr>
      {% } %}
    </script>
```

Thank you very much.

**Comment by blueimp** [comment]
Hello @oliverbob,

the [template library](https://github.com/blueimp/JavaScript-Templates) used for the demo has one advantage - it's very small with **1KB** (and even smaller if you use [compiled templates](https://github.com/blueimp/JavaScript-Templates#compiled-templates)).
It also does not introduce its own templating language, but is just using JavaScript code separated by `{%` and `%}` tags (which are configurable if you prefer something else).

However I'm certainly not forcing anyone to use my template library. I simply needed something which makes managing the upload/download templates for the demo a bit more manageable than just using jQuery, and back in 2011 when I first introduced it, React didn't exist yet.

Right on the main page of the [Wiki](https://github.com/blueimp/jQuery-File-Upload/wiki) is a section for [customization how-tos](https://github.com/blueimp/jQuery-File-Upload/wiki#customization-how-tos).
The second link in this section leads to a page about using a different [Template Engine](https://github.com/blueimp/jQuery-File-Upload/wiki/Template-Engine) and even comes with an example using jQuery, so exactly what you're asking for.
