### ISSUE TITLE
demo to other site

### ISSUE THREAD

**Issue by softboy99** [blueimp/jQuery-File-Upload#3629]
Hi
I'm in china, your demo are blocked cannot be open, Could you please upload it to another site? Thanks a lot.

**Comment by blueimp** [comment]
Hi @softboy99,
I guess you are referring to the server-side demo, which runs on [Google App Engine](https://appengine.google.com/) on an appspot.com domain ([which is blocked in China](https://en.wikipedia.org/wiki/Websites_blocked_in_mainland_China)).

Google App Engine has served me well over the years and I'm not gonna increase my maintenance burden by deploying it to another provider at this point.

What you can do instead to try out the demo is the following:
- [Install Docker](https://docs.docker.com/get-docker/)
- Download this repo to your local machine
- Run `docker-compose up -d` in the folder for this project
- Go to http://localhost and enjoy ☺️
