### ISSUE TITLE
Basic-plugin

### ISSUE THREAD

**Issue by precision1980** [blueimp/jQuery-File-Upload#3631]
Your basic plugin only works on mobile. I have tried a few different solutions pass the data and seems to now want to work. Maybe there is something I am missing?

https://github.com/blueimp/jQuery-File-Upload/wiki/Basic-plugin

**Comment by precision1980** [comment]
figured it out... by adding the form around the element it works on desktops. without the form, it only works on mobile. sorry for the bug. login day brain isn't working well.

<form>
	<input id="fileupload" type="file" name="files[]" multiple>
</form>

**Comment by precision1980** [comment]
```
<form>
	<input id="fileupload" type="file" name="files[]" multiple>
</form>
```

**Comment by blueimp** [comment]
Can you report on which desktop browser and operating system version you tested the basic plugin example code?
Desktop browsers should also be able to handle file upload selections without a surrounding HTML form.

**Comment by blueimp** [comment]
Tentatively closing this as non-reproducible, however we can reopen if it should be clearly identified as a bug in the library.

**Comment by precision1980** [comment]
I have been able to reproduce it on all systems that are windows 7 and newer.

**Comment by precision1980** [comment]
as long as I use the form as a wrapper and call the id of the form it works on every system.

`																<form id="fileupload" action="/upl" method="POST" enctype="multipart/form-data" class="">
																	<input id="fileupload" class="file-input" type="file" name="files[]" accept="image/jpeg,image/jpg,image/png,image/webp,image/gif,video/mp4,video/ogg,video/webm" style="display: none;" multiple="">
																</form>`

**Comment by precision1980** [comment]
I modified a few more lines in the class to change the file name. Some applications might want smaller name lengths. I suggest creating a private function that someone can set the option in the class to make random name based on alphanumeric '0123456789AZ'.

**Comment by blueimp** [comment]
Here's a demo using the basic plugin:
https://fiddle.jshell.net/em7jwgtf/show/

It initiates the file upload widget directly on the file input field and does not use a surrounding form.

I've tested it successfully on Chrome, Firefox and Safari on macOS Catalina as well as Internet Explorer 11, Edge Legacy and Edge (Chromium) on Windows 10.

**Comment by precision1980** [comment]
Your fiddle allows me to open it on my phone but not on my windows systems.

**Comment by blueimp** [comment]
Could you elaborate what exactly happens on your Windows systems?
If you can, a step-by-step explanation, any error messages from the console or potentially a video recording or screenshots would help.
