### ISSUE TITLE
The jQuery referenced in demo

### ISSUE THREAD

**Issue by liukefu2050** [blueimp/jQuery-File-Upload#3632]
The jQuery referenced in demo can't be accessed in other cases, such as China. 
Can you use the local version？

url：http://blueimp.github.io/jQuery-File-Upload/
jquery：https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js

thanks

**Comment by blueimp** [comment]
Hi @liukefu2050,
the server-side of the demo runs on [Google App Engine](https://appengine.google.com/) on an appspot.com domain, [which is blocked in China](https://en.wikipedia.org/wiki/Websites_blocked_in_mainland_China), so even if I add a local jQuery fallback, you won't be able to use it.

What you can do instead to try out the demo is the following:
- [Install Docker](https://docs.docker.com/get-docker/)
- Download this repo to your local machine
- Run `docker-compose up -d` in the folder for this project
- Go to http://localhost and enjoy ☺️ 

Please also see #3629
