### ISSUE TITLE
Multiple dropzones adds files twice

### ISSUE THREAD

**Issue by luisfdgon** [blueimp/jQuery-File-Upload#3634]
Hi.

I'm implementing a multi dropzone logic like this:

```
<div id="mainFolder" class="dropzone">
  <div id="folder1" class="dropzone"></div>
  <div id="folder2" class="dropzone"></div>
</div>
```

The dropzone class is configured as dropZone in the upload settings.

The issue is: When dropping files into the mainFolder div, it works well. When dropping files into folder1 or folder2 it uploads the files twice, because it assumes that was dropped into mainfolder as well.

**Comment by blueimp** [comment]
While I would recommend to not set up nested drop zones, you can stop event propagation to bubble up to parent elements using [event.stopPropagation()](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation), e.g.:

```js
$('#fileupload').on('fileuploaddrop', function (e, data) {
  if ($('#folder1')[0].contains(e.delegatedEvent.target) || $('#folder2')[0].contains(e.delegatedEvent.target)) {
    e.stopPropagation();
  }
})
```

Please also see #2190
