### ISSUE TITLE
Image Stuck In Processing...

### ISSUE THREAD

**Issue by tdeveloper2020** [blueimp/jQuery-File-Upload#3638]
![10458-1](https://user-images.githubusercontent.com/64659447/80831760-44970e80-8ba0-11ea-921b-4ff835ebe3e9.jpeg)
![10458-1H](https://user-images.githubusercontent.com/64659447/80831772-495bc280-8ba0-11ea-99d6-7ede3aa7890e.jpg)

The first image gets stuck in a "processing state..." state. Only images from this camera end up doing this. I exported the file in PhotoShop and it worked, this is the second file. The file is valid and saved from a Canon PowerShot camera, any ideas why only this file wouldn't work?

When you test this if you upload the first image you cannot upload the second image. However, if you start with the second image it works just fine.

**Comment by blueimp** [comment]
Closing in favor of the duplicate #3639 (since there are more user comments).

**Comment by zubinnt** [comment]
what is the fix for this issue,  i have this also

**Comment by blueimp** [comment]
@zubinnt Same as https://github.com/blueimp/jQuery-File-Upload/issues/3639#issuecomment-667013950.

**Comment by zubinnt** [comment]
ah ,  it dont work for me now,  i did a small modification

i put this line on the upload form

    $('#fileupload').fileupload({
        url: url,
        dataType: 'json',

        formData: [{ name: 'custom_dir', value: 'UKKQZZSRVG' }],


        autoUpload: false,
        acceptFileTypes: /(\.|\/)(jpg|jpeg|png|Jpeg|JPEG|JPG|Png|PNG)$/i,
        maxFileSize: 10000000, // 10 MB


and mod the php file handler,   so it makes my custom dirs,  works on the
old version,  didnt manage to get it working on the new version.


    protected function get_user_path() {
        if ($this->options['user_dirs']) {

            $custom_dir = $_REQUEST['custom_dir'];

            return  $custom_dir  .'/';
        }
        return '';
    }

**Comment by blueimp** [comment]
@zubinnt, please see #2190
