### ISSUE TITLE
BlueImg jQuery Image upload not working for specific images

### ISSUE THREAD

**Issue by umairm638** [blueimp/jQuery-File-Upload#3639]
I'm facing a very strange issue that some of the images aren't uploading using this plugin After selecting these image nothing happen, no ajax call or any error appear in console.

I've increase upload limit on server as well. Attached is the image which is not uploading and the code I'm using.

![BERGAMOT01](https://user-images.githubusercontent.com/24369007/80837648-aabb7a00-8c10-11ea-8f72-d54f7a4dc041.jpg)

       $('#fileupload').fileupload({
        dataType: 'json',
        autoUpload: true,
        url: '<?php echo base_url(); ?>/user/upload_img',
        acceptFileTypes: /(.|\/)(gif|jpe?g|png|tif)$/i,
        maxFileSize: 999000,
        beforeSend: function() {
            console.log('before send called');
            $(".hidebutton").hide();
            $(".showContinue").show();
            $(".confirmationImages").addClass('ConfirmationAlert');
        },
        always: function (e, data) {           
            var count=parseInt($("#output").html());
            count= count+data.files.length;
            $("#output").html(count);
        },
        complete: function() {
            $(".hidebutton").hide();
            $(".showContinue").show();

        }
    }).on('fileuploaddone', function (e, data) {
        var activeUploads = $('#fileupload').fileupload('active');
        if(activeUploads == 1) {
            $(".confirmationImages").removeClass('ConfirmationAlert');
        }
    }).on('fileuploadadd', function (e, data) {
        console.log('file added');
    });

File added appear in console after selecting file, but after that nothing happen. Thanks!

**Comment by nathan-dealerwebs** [comment]
We have had the same issue come out of no where today, just not uploading for certain images. We have trawled through our code but haven't changed anything in months and was all working.

**Comment by umairm638** [comment]
@nathan-dealerwebs  yes it just came out of no where, and the weird thing is that this same image is getting uploaded on demo website given here.

**Comment by tdeveloper2020** [comment]
Same problem here, see my other thread.

**Comment by umairm638** [comment]
@tdeveloper2020  please share that thread's link here. Thanks!

**Comment by nathan-dealerwebs** [comment]
@umairm638 https://github.com/blueimp/jQuery-File-Upload/issues/3638

**Comment by tdeveloper2020** [comment]
https://github.com/blueimp/jQuery-File-Upload/issues/3638

**Comment by tdeveloper2020** [comment]
Also, we found the exact same thing, if we exported it in Photoshop it worked. Example in #3638 with the one that worked and the one that didn't.

**Comment by blueimp** [comment]
Hi everyone,

there have been breaking changes in the (optional) [blueimp-load-image](https://github.com/blueimp/JavaScript-Load-Image) dependency regarding Exif Thumbnail data handling: cb6943f (see also [this comment](https://github.com/blueimp/JavaScript-Load-Image/issues/107#issuecomment-622464690) on the nature of the breaking changes).

The dependency is required for the [image processing plugin](https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-image.js), but [marked as optional](https://github.com/blueimp/jQuery-File-Upload/blob/888852709bd74c649d7d55287c870d47d53dcea1/package.json#L42) as it's not required for the [basic plugin](https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload.js).

My assumption is that you're including this dependency directly from GitHub as in the demo?
(search for https://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js in your source code)

If you've followed the [setup guide](https://github.com/blueimp/jQuery-File-Upload/wiki/Setup) there's a note at the top regarding inclusion of external dependencies:
> Although the demo implementations contained in this repository include source files from remote servers, it is recommended to download all dependencies and upload them to your own server.

The reason for this note is such breaking changes in those external dependencies, it's strongly recommended to include them in your project via [NPM](https://www.npmjs.com/) or other means.

How to fix this:
- Upgrade to the latest version of jQuery File Upload (it accounts for the breaking changes in it's image processing plugin)
- Or include a static older (<5) version of [blueimp-load-image](https://github.com/blueimp/JavaScript-Load-Image) in your projects.

Please let me know if this helps so we can close this issue.

**Comment by umairm638** [comment]
Hi @blueimp  thanks for your response.

I've tried by including blueimp-load-image version 4, it has now started uploading jpg images but still getting issue with JPG and TIF files.

You were right the previously this file was directly included from GITHUB.

**Comment by blueimp** [comment]
Please test the problematic images on this demo page:
https://blueimp.github.io/JavaScript-Load-Image/

If they fail to load there it’s an issue in [blueimp-load-image](https://github.com/blueimp/JavaScript-Load-Image) and I would appreciate if you could file an issue in that project with links to the reference images.

Otherwise I would recommend you to update to the latest version of both projects and see if that solves the issue.

**Comment by stijink** [comment]
Hi,

same problem here. Not sure if this an issue with the load-image plugin or the jquery-image-upload plugin. As this github issue describes the problem very well, i will comment on this one.

I've tried with this plugin versions:
```
"blueimp-file-upload": "10.20.0",
"blueimp-load-image": "5.5.0",
```

The problematic image file can be found here:
https://drive.google.com/open?id=1FUE1Ztg_xBuSSDNYlFv_yQa61-ij0qyL

The image has been edited with Adobe photoshop.

Stephan

**Comment by lleitner-hub** [comment]
> 
> 
> Hi everyone,
> 
> there have been breaking changes in the (optional) [blueimp-load-image](https://github.com/blueimp/JavaScript-Load-Image) dependency regarding Exif Thumbnail data handling: [cb6943f](https://github.com/blueimp/jQuery-File-Upload/commit/cb6943f1704b2be799ba7e8866bb5199ab92baa5) (see also [this comment](https://github.com/blueimp/JavaScript-Load-Image/issues/107#issuecomment-622464690) on the nature of the breaking changes).
> 
> The dependency is required for the [image processing plugin](https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-image.js), but [marked as optional](https://github.com/blueimp/jQuery-File-Upload/blob/888852709bd74c649d7d55287c870d47d53dcea1/package.json#L42) as it's not required for the [basic plugin](https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload.js).
> 
> My assumption is that you're including this dependency directly from GitHub as in the demo?
> (search for https://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js in your source code)
> 
> If you've followed the [setup guide](https://github.com/blueimp/jQuery-File-Upload/wiki/Setup) there's a note at the top regarding inclusion of external dependencies:
> 
> > Although the demo implementations contained in this repository include source files from remote servers, it is recommended to download all dependencies and upload them to your own server.
> 
> The reason for this note is such breaking changes in those external dependencies, it's strongly recommended to include them in your project via [NPM](https://www.npmjs.com/) or other means.
> 
> How to fix this:
> 
>     * Upgrade to the latest version of jQuery File Upload (it accounts for the breaking changes in it's image processing plugin)
> 
>     * Or include a static older (<5) version of [blueimp-load-image](https://github.com/blueimp/JavaScript-Load-Image) in your projects.
> 
> 
> Please let me know if this helps so we can close this issue.

I had the same issue!
Thanks! This solved the problem. I referenced somewhere  https://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js. So i downloaded a older version from it and now it works perfectly fine, as always. 
I just don't wanted to do an update, cause then, I would had to do a adjustment on my custom template.

**Comment by blueimp** [comment]
Thanks a lot for providing the problematic image @stijink!
It allowed me to identify the issue and release a fix (new minor version of `blueimp-load-image`).

That image has a Thumbnail directory (IFD1), but the thumbnail length is set to `0`.
In such a case, `blueimp-load-image` returned the original Thumbnail offset instead of a Blob, which did not evaluate as `falsy` value (offsets are positive integers) and led to issues in jQuery File Upload's image processing.
The new version of `blueimp-load-image` now returns `undefined` for the Thumbnail `Blob` in those cases, which fixes the issue in jQuery File Upload.

**Comment by stijink** [comment]
@blueimp Thank you very much for the fast response and the fix. I'll integrate it right away :)

**Comment by blueimp** [comment]
I'm closing this issue as fixed.
If you still have related issues, please feel free to post further comments here.

**Comment by zubinnt** [comment]
> I'm closing this issue as fixed.
> If you still have related issues, please feel free to post further comments here.

i just realised i have this problem,  what do i need to do to fix it ?

**Comment by blueimp** [comment]
@zubinnt, in the case of this issue here, the fix was to update to the latest version of [blueimp-load-image](https://github.com/blueimp/JavaScript-Load-Image), which is an optional dependency for jQuery File Upload if you need image processing capabilities.

**Comment by zubinnt** [comment]
thanks for the reply,  i did replace all the js files,  do we need to
change anything on the upload landing page ?

z

**Comment by blueimp** [comment]
Nope, not for this fix.

**Comment by DinalieLiyanage** [comment]
Hi there,

I came up with an error while loading .tiff files via blueImp. Do you have a list of unsupported file types with this blueImp or can it be fixed?

**Comment by zubinnt** [comment]
You can specify any file type to accept in the script Tif, tiff, etc.  I
think the spelling of the extension may play a part.

Z

**Comment by blueimp** [comment]
@DinalieLiyanage 

You can configure the accepted file types in jQuery File Upload (on the client side) with the following option:
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#acceptfiletypes

e.g. the [demo](https://blueimp.github.io/jQuery-File-Upload/) restricts the list to common image types:
https://github.com/blueimp/jQuery-File-Upload/blob/7e655a866677184412fe16a512c61c547a1e875c/js/demo.js#L42

On the server-side, if you're using the sample PHP upload handler, you can configure the accepted files with the `accept_file_types` option:
https://github.com/blueimp/jQuery-File-Upload/blob/7e655a866677184412fe16a512c61c547a1e875c/server/php/UploadHandler.php#L104

Please note that image previews are only supported for file types that are supported by the browser, which usually excludes TIFF files.

**Comment by iliyanz** [comment]
If upload not working for specific images then you have to clear EXIF  . I used this tool and it worked http://www.exiferaser.com/
I spent whole day checking from website to php and server , then I found out the images had lots of meta data which breaks image preview, so I cleared it and its working.
