### ISSUE TITLE
can you stop tag every commit ? 

### ISSUE THREAD

**Issue by sergiomb2** [blueimp/jQuery-File-Upload#3640]
look into this guys [1] just did a tag after   3415 commits  ... 

https://github.com/PCSX2/pcsx2/releases/tag/v1.5.0-dev

**Comment by blueimp** [comment]
Thanks for your suggestion @sergiomb2.

While I understand the maintenance burden of updating dependencies, you are not forced to update.

Receiving changes early allows dependent projects to receive fixes early.
e.g. most of the recent commits are related to fixes for automatic image orientation in the optional `blueimp-load-image` dependency.

**Comment by sergiomb2** [comment]
look at this guys https://github.com/tvheadend/tvheadend/releases :smile:
