### ISSUE TITLE
Stalls at Processing... on upload from iPhone Chrome

### ISSUE THREAD

**Issue by RentalGauge** [blueimp/jQuery-File-Upload#3642]
When I try to upload an existing picture from the camera roll on my iPhone using Chrome my website shows the spinner, filename and "Processing...." text but does not get any further--endless loop (see attached pic). If I take a picture with the camera on the spot that seems to work. On my desktop Mac using Chrome I see the preview image almost right away and the add files and upload buttons  always work. I am having trouble uploading images from a variety of mobile devices and browsers (chrome, safari, iphone, samsung, etc.). Is anyone else having the same issue on mobile?

Here are the libs I'm using:
Website:
- php v7.3, codeigniter v3.1.11, jquery v3.2.1, bootstrap 3.3.7, blueimp jquery file upload 10.23.0
Mobile device:
- iPhone 6 running iOS v13.3, mobile Chrome v81.0.4044.124

Any help would be greatly appreciated.

![blueimp-jfu](https://user-images.githubusercontent.com/65119364/81501987-2e2c3980-92a9-11ea-94b8-e8d827075fcf.png)

**Comment by blueimp** [comment]
Thanks for your report @RentalGauge.

Can you reproduce this issue on the [demo page](https://blueimp.github.io/jQuery-File-Upload/)?

Otherwise you might wanna upgrade to the latest version (including dependencies) and have a look at #3639.

**Comment by RentalGauge** [comment]
The demo page worked perfectly on my iPhone. Thank you for pointing me in that direction.

I noticed that the demo code uses jQuery 1.12.4. My project was linking to jQuery 3.2.1. When I linked my project to jQuery 1.12.4, jquery file uploader worked!!

Is there a way to make jquery file uploader work with a more recent version of jQuery? Or is there a way to determine what the latest version of jQuery that jfu works with? I'm worried that some other feature of my site depends on features only found in jQuery 2x or 3x. Thanks again.

**Comment by blueimp** [comment]
jQuery File Upload should definitely work with jQuery 3.2.1 as well - in fact the demo was set up with that version until very recently and has only been downgraded to be able to test old browser versions: 562354b

Could you provide more details on what did not work with jQuery 3.2.1?
e.g. error messages, step-by-step examples on how to reproduce the issue.

You can also run the demo locally - all you need is Docker - and change the jQuery script section to the following to try to reproduce any issues isolated to this project:

```html
<script
  src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"
  integrity="sha384-vk5WoKIaW/vJyUAd9n/wmopsmNhiy+L2Z+SBxGYnUkunIxVxAv/UtMOhba/xskxh"
  crossorigin="anonymous"></script>
```

**Comment by blueimp** [comment]
Closing this as not reproducible with the demo.
