### ISSUE TITLE
error to upload HEIF format files

### ISSUE THREAD

**Issue by kainpro** [blueimp/jQuery-File-Upload#3643]
Hello good evening this type of new HEIF format, can the blueimp already support this type of format?

additional I'm having trouble uploading photos taken with the phone camera option.

I already updated my file which was out of date jquery.fileupload-image.js And still some phones has the problem.

phones that take photos in HEIF format

**Comment by blueimp** [comment]
jQuery File Upload can handle any file type.

For security reasons, the demo server-side file upload handlers restrict uploads to common image formats (JPEG, GIF and PNG), but you can change this setting:
https://github.com/blueimp/jQuery-File-Upload/blob/90743ce2dd690c84407a39ce814e580a6102380f/server/php/UploadHandler.php#L97-L104

Please note that no Browser supports displaying HEIC files as of now.
