### ISSUE TITLE
Async call during "send" event?

### ISSUE THREAD

**Issue by david-hollifield** [blueimp/jQuery-File-Upload#3647]
I need to make an ajax call into my server for each file in order to get a signature to upload to AWS. I use to get these signatures in the "add" event, but these signatures have a time limit and if the user is uploading a bunch of large files, the signature for a later file can fail due to the AWS signature time limit being exceeded. Being able to get that signature just before a file is uploaded would be ideal and the "send" event looks like the best place for that. Unfortunately, it only supports returning false from the event to cancel the upload. It would be great if you could return a promise from the "send" event that would wait to be resolved before continuing the upload.

I have a fork that does exactly that by adding a promise to the options object passed into the "send" event and the file upload code has been updated to look for that promise and postpone the upload until that promise is resolved. It's a bit of a hack and it works great, but I'd like to not have to maintain the fork and more easily stay up-to-date with the core project.

Is there another way to accomplish what I'm trying to do? 

Thanks!

**Comment by blueimp** [comment]
Hi @david-hollifield,
there's a wiki page dedicated to submitting files asynchronously and it also has a section on using the `submit` callback as alternative to the `add` callback:
https://github.com/blueimp/jQuery-File-Upload/wiki/Submit-files-asynchronously#using-the-submit-callback-option

**Comment by david-hollifield** [comment]
Thanks @blueimp. I'll check it out. I can't believe I missed that. DOH!

**Comment by blueimp** [comment]
No worries, unfortunately the GitHub wiki is missing a good search function.
