### ISSUE TITLE
Can this lib support Angular7

### ISSUE THREAD

**Issue by xiantailang5532** [blueimp/jQuery-File-Upload#3649]
I want to use the jQuery-File-Upload,But my project is used Angular7.
Can I use the jQuery-File-Upload, How to Import this lib for my project?

**Comment by blueimp** [comment]
Hi @xiantailang5532,

I'm not aware of an Angular 7 plugin that incorporates this project.
However if you find one or plan to implement one yourself, please post a link here, then I'll gladly add it to the [Wiki](https://github.com/blueimp/jQuery-File-Upload/wiki).

**Comment by xiantailang5532** [comment]
Hi @blueimp 
I also can not import the jQuery-File-Upload into my appmodule.
But I Execute [npm install jquery --sav],[npm i @types/jquery],[npm install blueimp-file-upload --save],the three command,and added this code into my angular.json ,the basic Upload can worked.
 "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
　　　。。。
            "scripts": [
              "node_modules/blueimp-file-upload/js/vendor/jquery.ui.widget.js",
              "node_modules/blueimp-file-upload/js/jquery.fileupload.js"
            ]
         }
      }

**Comment by blueimp** [comment]
Closing this, as it's unlikely that I will provide an Angular version myself.
