### ISSUE TITLE
Doesn't seem to work on localhost

### ISSUE THREAD

**Issue by boionfire81** [blueimp/jQuery-File-Upload#3650]
I uploaded the files, added require file then 
$upload_handler=new UploadHandler(); underneath the require.

And my page returns as a text document print out. If I remove

$upload_handler=new UploadHandler();

then the  page echo's out like normal. Is it an issue with running on a localhost/wamp server?

Fortunately my error reporter was running in the background and searching through all the text I found a few of the errors that came through:

Undefined index: HTTP_REFERER line 1234
Undefined index: download line 1230
Undefined index: file line 1230
Undefined index: upload_dir line 254
Undefined index: redirect line 1226
Undefined index: HTTP_CONTENT_RANGE 1234

**Comment by blueimp** [comment]
Hi @boionfire81,

The PHP file upload handler supports any server hostname (including `localhost`), but I have not tested it running under Windows (assuming Windows from [WAMP](https://en.wikipedia.org/wiki/WampServer)).

However the line numbers from your error log do not seem to correspond with the actual lines of code in [UploadHandler.php](https://github.com/blueimp/jQuery-File-Upload/blob/master/server/php/UploadHandler.php).

If you're fine with installing [Docker for Windows](https://docs.docker.com/docker-for-windows/install/), you can test this project by running the following command in the project directory:

```sh
docker-compose up -d example
```

Next you should be able to access the server via http://localhost.

**Comment by blueimp** [comment]
Closing this as support request (see also #2190).
