### ISSUE TITLE
After introducing custom user_path delete image does not work

### ISSUE THREAD

**Issue by startupper73** [blueimp/jQuery-File-Upload#3653]
Hey blueimp.
You have created awsome code, but I have an issue.

I have introduced a custom path to which files are uploaded and slightly changed the get_user_path the UploadHandler class. Upload works fine, but delte does not work.
Any idea ? 
Many Thanks!

protected function get_user_path() {
        if ($this->options['user_dirs']) {
            return $this->get_user_id().'/';
        }
        return $this->objectid.'/';
    }

**Comment by blueimp** [comment]
Hi @startupper73,

`get_user_path()` is used by `get_upload_path` which in turn is used by the `delete` method:
https://github.com/blueimp/jQuery-File-Upload/blob/53992c2ddf43b0f43465d1a55c64d8ca02657118/server/php/UploadHandler.php#L1452-L1474
You probably wanna specifically debug this line here:
https://github.com/blueimp/jQuery-File-Upload/blob/53992c2ddf43b0f43465d1a55c64d8ca02657118/server/php/UploadHandler.php#L1460

Please also see #2190
