### ISSUE TITLE
Bundle with webpack causes module not found errors

### ISSUE THREAD

**Issue by ko2in** [blueimp/jQuery-File-Upload#3655]
When I imported the `jquery.fileupload-ui` and bundled with webpack, webpack yields the build errors which say some modules couldn't be found. Here is a line of the error from webpack.
```
ERROR in ./node_modules/blueimp-file-upload/js/jquery.fileupload-image.js
Module not found: Error: Can't resolve 'canvas-to-blob' in '/home/koko/Desktop/webpack/node_modules/blueimp-file-upload/js'
```
There are three files that are producing these kind of errors: `jquery.fileupload-audio.js`, `jquery.fileupload-image.js` and `jquery.fileupload-video.js`.

Here's the source from `jquery.fileupload-audio.js` which return the error:
```
if (typeof define === 'function' && define.amd) {
    // Register as an anonymous AMD module:
    define([
      'jquery',
      'load-image',
      'load-image-meta',
      'load-image-scale',
      'load-image-exif',
      'load-image-orientation',
      'canvas-to-blob',
      './jquery.fileupload-process'
    ], factory);
  }
```
I modified as below and webpack builds my bundle successfully.
```
if (typeof define === 'function' && define.amd) {
    // Register as an anonymous AMD module:
    define([
      'jquery',
      'blueimp-load-image/js/load-image',
      'blueimp-load-image/js/load-image-meta',
      'blueimp-load-image/js/load-image-scale',
      'blueimp-load-image/js/load-image-exif',
      'blueimp-load-image/js/load-image-orientation',
      'blueimp-canvas-to-blob',
      './jquery.fileupload-process'
    ], factory);
  }
```
I am not too much familiar with AMD. It seems that they're using the incorrect namespace of dependencies.

**Comment by blueimp** [comment]
Hi @ko2in,

you should be able to use the [webpack resolve config](https://webpack.js.org/configuration/resolve/) for that.

There's also a post on StackOverflow that has some alternative solutions:
https://stackoverflow.com/questions/31849476/how-to-use-blueimp-file-upload-with-webpack

**Comment by ko2in** [comment]
Hi @blueimp Thanks. I've resolved using webpack resolve alias config. I'm closing this.
