### ISSUE TITLE
Upload not full speed

### ISSUE THREAD

**Issue by jazz1611** [blueimp/jQuery-File-Upload#3656]
Hello,

I'm facing uploading not full speed. Normal POST upload i can get full 100Mbps per file in tab browser. If i upload with per file per tab (3 tab total) can get full 300Mbps. Should i get full 300Mbps instead 100Mbps upload speed, i have set upload-chunk 10MB. What setting to fix it? Thank you.

![screenshot](https://user-images.githubusercontent.com/1846222/86527250-6033d380-bec7-11ea-9a05-9ab6629ba79d.png)

**Comment by blueimp** [comment]
If you upload multiple videos in one single POST request, you will always be faster than uploading chunks of those videos in many requests.
This is because for each request, you will have the overhead of establishing the HTTP connection (this is less of an issue with HTTP/2). With HTTPS, this also includes the overhead of establishing the TLS connection for reach request (less of an issue with TLS Session Resumption).

I don't think the combined overhead explains a 3x difference, but detecting the transfer speed of multiple requests is also not that accurate.

If you want to get the same speed as a single POST upload, you can do so with the option `singleFileUploads:false` and not setting `maxChunkSize ` - but then you also get all the drawbacks of a single POST upload.

**Comment by jazz1611** [comment]
if i upload one by one with setting `sequentialUploads: true`, i still get max 100Mbps instead 300Mbps. so it can be related to upload-chunk ?

**Comment by blueimp** [comment]
Yes, each chunk is one separate request and will incur an overhead cost.

**Comment by jazz1611** [comment]
so, no way to fix it? if use normal upload (without upload-chunk) with large file 10-20GB will be terrible/nightmare with move_uploaded_file. btw thank you

**Comment by blueimp** [comment]
If your server-side supports storing incomplete uploads, you could implement resumable uploads by setting the [uploadedBytes](https://github.com/blueimp/jQuery-File-Upload/wiki/Options#uploadedbytes) option to the number of bytes that have been uploaded successfully.
This way, you do not need to set the `maxChunkSize` option and can upload in one request.

See also:
https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads#resuming-file-uploads

**Comment by jazz1611** [comment]
hello, so it will work like as upload-chunk (not function move_uploaded_file), right?

**Comment by jazz1611** [comment]
seem it upload all file, although i was set `limitConcurrentUploads: 2`

![Screenshot_2](https://user-images.githubusercontent.com/1846222/86727667-d5cdaa00-c055-11ea-85d1-ef6b0d195566.png)

**Comment by blueimp** [comment]
The sample PHP upload server does not support resuming incomplete uploads unless chunked uploads are enabled on the client-side. So you will have to find and implement a different solution.

Your screenshot looks like you have set `singleFileUploads:false` or `limitMultiFileUploads:1`.
`limitConcurrentUploads` is for limiting concurrent uploads and does not influence how many files are included in one request.

**Comment by jazz1611** [comment]
hello, it mistake by my fault. everything is ok now. thank you so much.

**Comment by jazz1611** [comment]
can i ask you how to edit file name directly before submit "Start upload"?

**Comment by blueimp** [comment]
Sure, you can read how to do this here:
https://github.com/blueimp/jQuery-File-Upload/wiki/API#how-to-provide-alternative-file-names

Since your original question seems to be answered, I'll close this issue.
Please note that I don't provide any official support for this project, see also #2190.

**Comment by jazz1611** [comment]
Sorry, you mistake my mean. I mean edit file name as screenshot. If dont have, hope you can add this feature to project. thank you.
![Screenshot_5](https://user-images.githubusercontent.com/1846222/86787445-48a74700-c08f-11ea-9090-1544b779dd3f.png)
