### ISSUE TITLE
changing Scandir to MySQL result

### ISSUE THREAD

**Issue by rxhxtx** [blueimp/jQuery-File-Upload#3658]
Hi! 

im testing the pluging with MySQL integration like that:
https://github.com/blueimp/jQuery-File-Upload/wiki/PHP-MySQL-database-integration

but i cant change the scandir to a result in mysql..

alternatively I had tried it this way:

`protected function get_file_objects($iteration_method = 'get_file_object') {

        $upload_dir = $this->get_upload_path();

        if (!is_dir($upload_dir)) {

            return array();

        }

        $conn = new GetImg();
        $img = $conn->get_img();
        return array_values(array_filter(array_map(
            array($this, $iteration_method),
            $img
        )));
    }
`

`    function get_img()
    {
      $stmt = $this->pdo->prepare("SELECT * FROM `blueimp`");
        $stmt->execute();

        $array = array();
        while ($resp = $stmt->fetch(PDO::FETCH_ASSOC)) {
            array_push($array, $resp["name"]);
        }
        return $array;
    }`

does anyone know how I could replace the scandir with a mysql return from the original example? using this function:

`  protected function set_additional_file_properties($file) {

        parent::set_additional_file_properties($file);

        if ($_SERVER['REQUEST_METHOD'] === 'GET') {
        	$sql = 'SELECT `id`, `type`, `title`, `description` FROM `'
        		.$this->options['db_table'].'` WHERE `name`=?';
        	$query = $this->db->prepare($sql);
 	        $query->bind_param('s', $file->name);
	        $query->execute();
	        $query->bind_result(
	        	$id,
	        	$type,
	        	$title,
	        	$description
	        );
	        while ($query->fetch()) {
	        	$file->id = $id;
        		$file->type = $type;
        		$file->title = $title;
        		$file->description = $description;
    		}
        }
    }`

thank so much!!!

**Comment by blueimp** [comment]
Hi @rxhxtx,

unfortunately the issues ticker is not a good place for this question, as I don't provide any official support for this project.
Maybe you have better luck posting this question to StackOverflow.

Please see also #2190

**Comment by rxhxtx** [comment]
OK, sorry!!

I managed to do the CRUD by creating a class to manipulate the DB and the files without the need to use scandir.
Exist a suitable space for me to share the code for anyone who wants to learn and improve?
or isn't a good idea?

**Comment by blueimp** [comment]
Contributions are always welcome!
Unfortunately I had to disable write access to the Wiki due to spam, but you could post your guide in Markdown here as comment and I would add it to the Wiki (with proper attribution).
