### ISSUE TITLE
Time Remaining...

### ISSUE THREAD

**Issue by david-hollifield** [blueimp/jQuery-File-Upload#3659]
I was trying to resolve an issue with my time remaining display using the info from the Wiki and noticed the Demo page exhibits the same behavior. Notably it shows zero almost the entire time. I'm using the `(data.total - data.loaded) * 8) / data.bitrate` technique to get the number of seconds, but the bitrate is always so high that the value is almost 0 most of the upload and the upload takes several seconds to complete. A sample batch upload stats are attached. Is this a known bug or am I missing something? Thanks!

[upload stats.txt](https://github.com/blueimp/jQuery-File-Upload/files/4892556/upload.stats.txt)

**Comment by blueimp** [comment]
Hi @david-hollifield,
the remaining time is only calculated for the upload of bytes through the network, but most server-side implementations (including the sample ones) add additional processing time (e.g. for moving files and scaling images) after the upload itself is completed.
If you want to improve the UX, you could e.g. display a "processing" status after all bytes have been uploaded and before the request has been completed.

**Comment by blueimp** [comment]
Closing this as resolved due to no response.
