### ISSUE TITLE
UploadHandler.php

### ISSUE THREAD

**Issue by Vladislavik** [blueimp/jQuery-File-Upload#3661]
I am using chunk upload and some times on server I see hundred files from UploadHandler with names 
file (1).mp4
file (2).mp4
file (3).mp4
...
file (124).mp4
all files have the same size from one chunk
I think there is on some browsers wrong header with size or browser count file size incorrect, what I need to do to fix it?

**Comment by blueimp** [comment]
Hi @Vladislavik,

the issue could be on either or both client- and server-side.

This is the server-side function that creates new filename if the uploaded files is not recognized as a chunk:
https://github.com/blueimp/jQuery-File-Upload/blob/7e655a866677184412fe16a512c61c547a1e875c/server/php/UploadHandler.php#L505-L520

This is the server-side code that parses the complete file info from the content-range header:
https://github.com/blueimp/jQuery-File-Upload/blob/7e655a866677184412fe16a512c61c547a1e875c/server/php/UploadHandler.php#L1409-L1414

On client-side, the content-range header option is set here:
https://github.com/blueimp/jQuery-File-Upload/blob/7e655a866677184412fe16a512c61c547a1e875c/js/jquery.fileupload.js#L519

And the client-side code to define the content-range header string:
https://github.com/blueimp/jQuery-File-Upload/blob/7e655a866677184412fe16a512c61c547a1e875c/js/jquery.fileupload.js#L861-L862

I assume you followed the wiki page about chunked uploads?
https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads

**Comment by blueimp** [comment]
Closing this since there was no response in over a month.

**Comment by Luxury-666** [comment]
yes, I do all as on the wiki page about chunked uploads but some times there are millions of files with names (1), (2), (3) and etc, don't know how to fix it.

**Comment by Vladislavik** [comment]
yes, I do all as on the wiki page about chunked uploads but some times there are millions of files with names (1), (2), (3) and etc, don't know how to fix it.

**Comment by blueimp** [comment]
My recommendation to you is to add some logging to the respective functions I listed above.
Unfortunately, without a way to reproduce this I cannot support you further.

**Comment by apphancer** [comment]
I am experiencing the same issue from my end.

Server-side:

```
        $uploadHandler = new UploadHandler([
            'param_name'          => 'file',
            'upload_dir'          => '/www/documents/',
            'accept_file_types'   => '/\.(wav)$/i',
            'readfile_chunk_size' => 3 * 1024 * 1024, // 3 MiB
        ]);
        $data = $uploadHandler->post();
        exit;
```

**Comment by apphancer** [comment]
I am using Php 7.3, Chrome 85 and version 10.31.0 of the library.

The server-side is returning the following:

```
{
  "file": [
    {
      "name": "audio 10MB.wav",
      "size": 3000000,
      "type": "audio\/wav",
      "deleteUrl": "http:\/\/dashboard.localhost\/index.php?fil=audio%2010MB.wav",
      "deleteType": "DELETE"
    }
  ]
}{
  "file": [
    {
      "name": "audio 10MB (1).wav",
      "size": 0,
      "type": "audio\/wav",
      "deleteUrl": "http:\/\/dashboard.localhost\/index.php?fil=audio%2010MB%20%281%29.wav",
      "deleteType": "DELETE"
    }
  ]
}
```

**Comment by minamoto19** [comment]
Try commenting out this part:

            if (!multipart || options.blob || !this._isInstanceOf('File', file)) {
                options.headers['Content-Disposition'] = 'attachment; filename="' +
                    encodeURI(file.uploadName || file.name) + '"';
            }

on jquery.fileupload.js
lines 521+

**Comment by apphancer** [comment]
The problem - at least in my case - was with the PHP backend executing the post() method twice. 
I got things working by not calling the post() method. Unexpectedly, the constructor already does the job as by default it is set to run the post() method. It's not what one would except a constructor to do, but there you go.
Alternatively, the $initialize parameter of the constructor can be set to false and then the post() method can be manually called.
