### ISSUE TITLE
Compability with Bootstrap 4.5

### ISSUE THREAD

**Issue by AnNajib** [blueimp/jQuery-File-Upload#3662]
to-be-upload file not showing when using Bootstrap 4.5. Not only that, progress-bar has problem too. can you fix that? I wonder why nobody mention it, this compatibility problem has been here since a thousand years ago ...: v

**Comment by blueimp** [comment]
Hi @AnNajib,

Bootstrap 3 is still officially supported and has better support for older browsers, which is an important part for this project's continued existence too, so it's unlikely that I will add official support for Bootstrap 4 anytime soon.

With the exception of the [UI library](https://github.com/blueimp/jQuery-File-Upload/blob/master/js/jquery.fileupload-ui.js), all of this project can be used as-is with any version of Bootstrap.

If someone would like to maintain a fork that works with Bootsrap 4, I'll gladly add a link to the Wiki.
I'll mark this issue as a feature request so it doesn't get buried.

**Comment by blueimp** [comment]
Looking at older issues, it seems like this did come up in the past: https://github.com/blueimp/jQuery-File-Upload/issues/3537

Please check if setting the following option still works with Bootstrap 4:
```js
  $('#fileupload').fileupload({
    showElementClass: 'show/'
  });
```

**Comment by blueimp** [comment]
I've added this to the [style guide documentation](https://github.com/blueimp/jQuery-File-Upload/wiki/Style-Guide#bootstrap-ui) and will close this issue for now.

Please let me know if there should be issues beyond the `showElementClass`.

**Comment by AnNajib** [comment]
bootstrap moves forward to 5. please consider increasing the styling.

**Comment by AnNajib** [comment]
thanks for respond.

**Comment by rsmith013** [comment]
This didn't work for me. I found this setting digging through the code but setting it didn't seem to change the classes assigned to the element.
