### ISSUE TITLE
Chunked upload not resumed!

### ISSUE THREAD

**Issue by coder-amogh** [blueimp/jQuery-File-Upload#3663]
I just used this amazing library into my project and got stuck lot of times, but now it's perfectly alright. I just have one issue. I am using ChunkedUploader, because the file size would be too large (500 MB to 1 GB) to send in one go. The problem I am facing is that the ChunkedUploader is not able to resume the file upload. Whenever internet goes down, it detects the fail callback, but it doesn't resume it. 

I tried using code in this link: https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads#resuming-file-uploads but I think the server is not responding properly. I changed some code, to suit the project's need and now I just don't know if I have commented some code that was responsible for the chunked file resumable. 

Also as the server doesn't respond properly, after maxRetries, it stops and runs the stop callback code.  

Can anyone please let me know what part of the code is responsible for doing this? Unfortunately I cannot share the code. I am using PHP and Apache as the tech stack.

I need help with this as soon as possible because we can't deploy the project without this.

**Comment by blueimp** [comment]
Hi @coder-amogh, please see #2190.
