### ISSUE TITLE
Dose not work on Live Linux server, While it is working fine on localhost Xampp

### ISSUE THREAD

**Issue by mnafullstack** [blueimp/jQuery-File-Upload#3664]
I've tried to use it on my website which is currently under development and I am developing it on local host xampp server and this jquery file upload plugin works great. But when I upload the website to the live server which is Linux Cpanel, it is not working fine. Its showing the error while uploading any image. The error is: "Error File upload aborted". While the image is type is jpg and the size is just 2 kb. How to resolve it? please do let me know.

Thank you.

Note: I have not even customized the plugin.

**Comment by blueimp** [comment]
Hi @mnafullstack, please have a look here: #2190
