### ISSUE TITLE
show already uploaded files on page load

### ISSUE THREAD

**Issue by arapps3d** [blueimp/jQuery-File-Upload#3672]
Thanks for this awesome uploader and all the hard work!
Is there a possibility to show already uploaded files initially on page load -( just as if they have just been uploaded ) ?
(Sorry if this is not the right place for questions, not sure where else to ask)

In my use case files are uploaded into different subfolders for items.(subfolders are named with item no.- I figured this out thanks to the wiki - I edited the php upload handler ).

When an item is selected from a list, I want to display the uploader and the already uploaded files that exist in the subfolder for the selected item. 

I wonder if I have to write some custom php or maybe there is already a function for that(?).

**Comment by blueimp** [comment]
Sure that's possible, you can find an example implementation in the example PHP server-side file upload handler:
https://github.com/blueimp/jQuery-File-Upload/blob/7e655a866677184412fe16a512c61c547a1e875c/server/php/UploadHandler.php#L1379-L1394
If `user_dirs` are enabled, it will only return the current user's files.
You can adjust that code for your specific use case.

On the client-side, the `get` endpoint is called and the files are added the same way they're added when a file has been successfully uploaded:
https://github.com/blueimp/jQuery-File-Upload/blob/7e655a866677184412fe16a512c61c547a1e875c/js/demo.js#L56-L73

Please also see #2190.
