### ISSUE TITLE
multiple file uploads or widgets documentation are outdated

### ISSUE THREAD

**Issue by OnlineArts** [blueimp/jQuery-File-Upload#3673]
Hi, 

the publicly available documentation for 
https://github.com/blueimp/jQuery-File-Upload/wiki/Multiple-File-Input-Fields-in-One-Form
https://github.com/blueimp/jQuery-File-Upload/wiki/Multiple-File-Upload-Widgets-on-the-same-page
are both outdated.

I would really appreciate an update or straightforward guide to implement this based on the current demo implementation.

Cheers

Roman

### Edit:
Looks like I'm not the only one who is asking that:
file-upload-button

**Comment by blueimp** [comment]
Thanks for the heads up @OnlineArts.

I've updated and simplified the [Multiple File Input Fields in One Form guide](https://github.com/blueimp/jQuery-File-Upload/wiki/Multiple-File-Input-Fields-in-One-Form) as well as updated the [Multiple File Upload Widgets on the same page guide](https://github.com/blueimp/jQuery-File-Upload/wiki/Multiple-File-Upload-Widgets-on-the-same-page).
