### ISSUE TITLE
No improvement in compression

### ISSUE THREAD

**Issue by clickmeplz** [blueimp/jQuery-File-Upload#3676]
I checked first and last release for uploading an image with 2 MB size.
File size after upload at both releases are  402K. No improvement!
I was expecting some improvement in compression.

**Comment by blueimp** [comment]
Hi @clickmeplz,

this project does not implement any client-side image compression.

It does include support for client-side image resizing using [blueimp-load-image](https://github.com/blueimp/JavaScript-Load-Image) and uses [canvas.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) (with a polyfill for older browsers) to create Blob objects out of the resized canvas data.

[canvas.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) uses the image compression algorithms integrated into the browser for the respective file types (PNG, GIF, JPEG, WEBP).
