### ISSUE TITLE
No option to select camera and capture images on android Firefox v81.1.1

### ISSUE THREAD

**Issue by ashanrupasinghe** [blueimp/jQuery-File-Upload#3679]
It allowed us to select camera to capture images or record videos When click on brows button in old **Android** **Frefox** versions.
But latest version of Firefox (81.1.1) directly navigate user to selecting file options without providing camera option.
Any suggestion to fix this?

**Comment by blueimp** [comment]
Hi @ashanrupasinghe,

File input selection is a native browser function - you can control the input with the [capture attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Additional_attributes).

**Comment by blueimp** [comment]
Closing this as solved.
