### ISSUE TITLE
Video upload

### ISSUE THREAD

**Issue by pusty44** [blueimp/jQuery-File-Upload#3680]
Hi,
is there any option to make this script to upload large mp4 video? I'm trying to do this, but always I get error Empty file upload result. It happens only when video is larger than one chunk (20mb by default). Any idea how to make it work?

**Comment by blueimp** [comment]
Hi @pusty44,

do these entries in the FAQ help you out?

https://github.com/blueimp/jQuery-File-Upload/wiki/Frequently-Asked-Questions#what-is-the-maximum-file-size-limitation

https://github.com/blueimp/jQuery-File-Upload/wiki/Frequently-Asked-Questions#why-do-i-get-an-empty-file-upload-result-when-uploading-large-files-php

**Comment by blueimp** [comment]
Since there was no answer in 10 days, closing this as solved.
