### ISSUE TITLE
Submit all files in one request when submit button is clicked via jquery file upload and ASP.NET MVC Core

### ISSUE THREAD

**Issue by PingPongSet** [blueimp/jQuery-File-Upload#3681]
I use jquery-file-upload plugin below for user files upload.

https://github.com/blueimp/jQuery-File-Upload

The **problem** is that it sends one file at a time. 

I need to send all files via a request to server side when a Submit button is clicked. So I can carry out more operations after all uploaded files have been successfully uploaded to server side.

My current file below:

**Html (ASP.NET View)**

        <form id="fileupload" action="@Url.Action("UploadFiles")" method="POST" enctype="multipart/form-data">
            <div>
                <div class="drop formContentSection" id="dropArea">                    
                    <div class="fileupload-buttonbar">
                        <span class="btn fileinput-button button">
                            <span>Upload FILES</span>
                            <input type="file" name="file" multiple>
                        </span>
                        <span class="fileupload-process"></span>
                    </div>
    
                    
                    <table role="presentation" class="table table-striped">
                        <tbody class="files">
                        </tbody>
                    </table>
                </div>
    
            </div>
    
                <div class="fileupload-buttonbar">
                    <button type="submit" class="start">SUBMIT</button>
                </div>  
        </form>
    	
    	
    	
    <script id="template-upload" type="text/x-tmpl">
        {% for (var i=0, file; file=o.files[i]; i++) { %}
        <tr class="template-upload fade{%=o.options.loadImageFileTypes.test(file.type)?' image':''%}">
            <td>
                <p class="name">{%=file.name%}</p>
                <strong class="error text-danger"></strong>
            </td>
            <td>
                <p class="size">Processing...</p>
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
            </td>
            <td>
                {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start hidden" disabled>
                    <span>Start</span>
                </button>
                {% } %}
    
                {% if (!i) { %}
                <button class="btn btn-warning cancel btn-sharp">     
                    <span>Cancel</span>
                </button>
                {% } %}
            </td>
        </tr>
        {% } %}
    </script>
    
    
    <script id="template-download" type="text/x-tmpl">
        {% for (var i=0, file; file=o.files[i]; i++) { %}
        <tr class="template-download fade{%=file.thumbnailUrl?' image':''%}">
            <td>
                <p class="name">
                    {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                    {% } else { %}
                    <span>{%=file.name%}</span>
                    {% } %}
                </p>
                {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
                {% } %}
            </td>
            <td>
                <span class="size">{%=o.formatFileSize(file.size)%}</span>
            </td>
            <td>
                {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete btn-sharp" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}" {% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}' {% } %}>
                    <span>Delete</span>
                </button>
                {% } else { %}
                <button class="btn btn-warning cancel">
                    <span>Cancel</span>
                </button>
                {% } %}
            </td>
        </tr>
        {% } %}
    </script>
	
**JavaScript**

    	$(function () {
        'use strict';
    
        $('#fileupload').fileupload(
            {
                dataType: 'json',
                acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
                singleFileUploads: false,
                autoUpload: false
            });
    
        $('#fileupload').addClass('fileupload-processing');
        $.ajax({
            url: $('#fileupload').fileupload('option', 'url'),
            dataType: 'json',       
            context: $('#fileupload')[0]
        })
            .always(function () {
                $(this).removeClass('fileupload-processing');
            })
            .done(function (result) {
                $(this)
                    .fileupload('option', 'done')
                    .call(this, $.Event('done'), { result: result });
            });
    });

**Server side (Controller)**

      [HttpPost]
            public async Task<JsonFiles> UploadFiles(IFormFile[] file)  //it contains one element. I want all elements in one go
            {
    ...
    }

I tried below, which doesn't work

       <input type="file" name="file[]" multiple>

**Comment by blueimp** [comment]
Hi @PingPongSet,

You can disable the default single file upload handling with the following setting:
```js
$('#fileupload').fileupload({
  singleFileUploads: false
});
```
See also:
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#singlefileuploads

I cannot help you with the ASP.NET setup, but there are a couple of user contributed integration examples:
https://github.com/blueimp/jQuery-File-Upload/wiki#aspnet

**Comment by PingPongSet** [comment]
Hi @blueimp 

I have already disabled `singleFileUploads`. Please see my OP. But it is still not working.

**Comment by PingPongSet** [comment]
I put an index for each file via a hidden input before upload. 

For example, first file will have 

  <input type="hidden" value="0" name="currentNumber">
  <input type="hidden" value="2" name="totalNumber">


Second file will have 

  <input type="hidden" value="1" name="currentNumber">
  <input type="hidden" value="2" name="totalNumber">

The problem is that `currentNumber` is always zero on server side for all requests from Submit.

 <button type="submit" class="start savedcontinuebtn" onclick="return PopulateFileNumber()">SUBMIT</button>

  function PopulateFileNumber() {
        var $files = $("strong[class='error text-danger']:empty"); 
        $files.each(function(index){$(this).after('<input type="hidden" value="'+index+'" name="currentNumber"/><input type="hidden" value="'+$files.length+'" name="totalNumber"/>');});
    }

      sequentialUploads: true

**Server side**
   public async Task<JsonFiles> UploadFiles(IFormFile[] file, int hazardCaseId, int currentNumber, int totalNumber){
}

**Comment by blueimp** [comment]
Sorry I did not see that you were already setting this option It's easy to overlook your setting since you were posting your whole setup.

If you wanna share your setup, it's better to create a public demo and post a link.

Your code example should only include a most reduced version that highlights what's specific about your setup.

Setting `singleFileUploads:false` adds multi-file selections as-is to the queue, while the default setting (`singleFileUploads:true`) adds each individual file to the queue.

So if you're still selecting and adding files one by one, they will not be uploaded in one request if you're using the default User Interface.

If you want to allow single file selections that then get uploaded in one request, you will have to adjust the User Interface code.

One approach could be to add all selected files to a queue, e.g. by overriding the `add` option with your own function:
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#add

You could then trigger the upload with your own button and make use of the upload API:
https://github.com/blueimp/jQuery-File-Upload/wiki/API#programmatic-file-upload

Hope that helps.

Please also note that I do not provide any official support and usually close any issue posts that are considered support requests - see also #2190

**Comment by blueimp** [comment]
Closing as support request (see #2190).
