### ISSUE TITLE
Pass variables from referencing page to referenced JavaScript file with jquery-file-upload

### ISSUE THREAD

**Issue by PingPongSet** [blueimp/jQuery-File-Upload#3683]
I want to pass variables that can be used by `.fileupload()` below in a separate js file.

**main Html**

      <form id="fileupload" action="url here" method="POST" enctype="multipart/form-data">
        //I want to pass variables, e.g. count, that can be used by .fileupload() below
      </form/>
      
    <script src="~/js/fileUpload.js"></script>
   

**I want to pass variables**, e.g. `count`, that can be used by `.fileupload()` below

**fileUpload.js**

    $(function () {
        'use strict';
    
        $('#fileupload').fileupload(
            {
                dataType: 'json',
                acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
                singleFileUploads: false,
                autoUpload: false,
                sequentialUploads: true,
                always: function (result) {               
                   //use variables here which are passed from main Html
            });   
    });

**Comment by blueimp** [comment]
Please see #2190.
