### ISSUE TITLE
Request Timeout error when uploading file

### ISSUE THREAD

**Issue by kujain** [blueimp/jQuery-File-Upload#3684]
hi there!

When uploading files (roughly 20mb), consistently get failed error:
```
Request Timeout
Server timeout waiting for the HTTP request from the client.

Additionally, a 408 Request Timeout error was encountered while trying to use an ErrorDocument to handle the request.
```
This seems to be happening more and more often to me and now it's happening to all uploads. Earlier it would happen for very large files (40mb or so) and on slower connections. When I would simulate slower connection by chrome network throttling, I was able to recreate it. The failure happens at random times (from 15s to 30s etc.)

I adjusted all php-related settings, but I believe this has anything to do with PHP since the initial ajax request doesn't even complete and hand over to PHP. I added a timeout value as well (=10000000 or 0) but that didn't make any difference. This is on a shared hosting space so I cannot tweak apache-related settings like `RequestReadTimeout` or `KeepAliveTimeout`.

Here's my options for the fileupload:
```
    $('#fileupload').fileupload({
        url: large_url,
        dataType: 'json',
        autoUpload: false,
        acceptFileTypes: /(\.|\/)(tiff|tif)$/i,
        maxFileSize: 999000000,
        limitMultiFileUploads: 1,
        singleFileUploads: true,
        limitConcurrentUploads: 1,
        fileInput: '.largefile',
        maxNumberOfFiles: 1,        // Enable image resizing, except for Android and Opera,
        // which actually support image resizing, but fail to
        // send Blob objects via XHR requests:
        disableImageResize: true,
        previewMaxWidth: 100,
        previewMaxHeight: 100,
        previewCrop: true,
        maxRetries: 100,
        retryTimeout: 500,
        timeout: 10000000,
    }).on('fileuploadadd', function (e, data) {
        data.context = $('<div/>').appendTo('#files');
        $.each(data.files, function (index, file) {
            var node = $('<p/>')
                    .append($('<span/>').text(file.name));
            if (!index) {
                node
                    .append(uploadButton.clone(true).data(data));
            }
            node.appendTo(data.context);
        });
        var prog_bar = $(e.target).parent().parent().find('.progress');
        prog_bar.find('.progress-bar').removeClass('progress-bar-success');

    }).on('fileuploadprocessalways', function (e, data) {
        console.log(e, data);
        var index = data.index,
            file = data.files[index],
            node = $(data.context.children()[index]);
        if (file.preview) {
            node
                .prepend('<br>')
                .prepend(file.preview);
        }
        if (file.error) {
            node
                .append('<br>')
                .append($('<div class="text-danger"/>').text(file.error));
        }
        if (index + 1 === data.files.length) {
            data.context.find('button')
                .text('Upload')
                .prop('disabled', !!data.files.error);
        }
    }).on('fileuploadprogressall', function (e, data) {
        var progress = parseInt(data.loaded / data.total * 100, 10);
        $('#progress .progress-bar').css(
            'width',
            progress + '%'
        );
    }).on('fileuploaddone', function (e, data) {
        var prog_bar = $(e.target).parent().parent().find('.progress');
        prog_bar.find('.progress-bar').addClass(
            'progress-bar-success'
        );

        $.each(data.result.files, function (index, file) {
            if (file.url) {
                var link = $('<a>')
                    .attr('target', '_blank')
                    .prop('href', file.url);

                if (file.status === false) {
                    var status = '<div class="status red">'+file.message+'</div>';
                } else {
                    var status = '<div class="status">'+file.message+'</div>';
                    addLargeImage(file.thumbmailurl);
                }
                //var status = '<span class="status">Done</span>';
                $(data.context.children()[index])
                    .append(status);


            } else if (file.error) {
                var error = $('<div class="text-danger"/>').text(file.error);
                $(data.context.children()[index])
                    .append('<br>')
                    .append(error);
            }
        });
    }).on('fileuploadfail', function (e, data) {
        $.each(data.files, function (index) {
            var error = $('<div class="text-danger"/>').text('File upload failed.');
            $(data.context.children()[index])
                .append('<br>')
                .append(error);

            var prog_bar = $(e.target).parent().parent().find('.progress');
            prog_bar.find('.progress-bar').delay(3000).animate( { width: 0 } );
        });
    }).prop('disabled', !$.support.fileInput)
        .parent().addClass($.support.fileInput ? undefined : 'disabled')
    .bind('fileuploadsubmit', function (e, data) {
        data.formData = {
            'curr_entry_id': $('[name=curr_entry_id]').val(),
            'curr_ag_id': $('[name=curr_ag_id]').val()
        }
    });
```
Here's the XHR output in chrome (in firefox, it just fails without returning any error!):
![image](https://user-images.githubusercontent.com/120631/97124945-809ecc80-1708-11eb-990c-4f954b8f3363.png)

Is there anything I can do or try to get around this? I have been hesitant to use chunk files as that could really complicate the backend processing for this rather simple project! Hoping there is another better way...
Thanks very much!

jQuery-File-Upload v.10.29
jQuery v.2.2.3

**Comment by blueimp** [comment]
Thanks for your report @kujain.

When you disable JavaScript and submit a selected file with a plain HTML form submit, can you reproduce the same issue?

Since this project is rather old and has been well-tested over time (including with large file uploads), there is still a very good chance this is related to your backend setup (and not an issue with this project).
However it doesn't have to be your PHP setup, if the request doesn't reach PHP it might very well have something to do with a server in front (Apache in your case, or anything else that is between your clients and your backend).

If you can reproduce this with a plain HTML form submit, you probably wanna contact your shared hosting provider about it.

**Comment by kujain** [comment]
Hi @blueimp 

This WAS a server configuration issue actually. Disabling the `mod_reqtimeout` apache module resolve this. But considering that that module was added on the host for security purposes (DDOS etc) it would be good to find a solution that works with the module correctly. 

Thanks!

**Comment by blueimp** [comment]
Thanks for posting your resolution @kujain!

You probably don't want to disable the `mod_reqtimeout` module completely.
If you are able to set `RequestReadTimeout`, you could change the `body` timeout setting only and leave the remainder of the settings as default:
https://httpd.apache.org/docs/2.4/mod/mod_reqtimeout.html
