### ISSUE TITLE
Error getting on File Deletion

### ISSUE THREAD

**Issue by ManjuAbhijith** [blueimp/jQuery-File-Upload#3689]
while trying to delete an uploaded image ,getting an error "An error occurred: errornError: Unauthorized"
![err](https://user-images.githubusercontent.com/73826864/97861816-611c2b00-1d2a-11eb-8ed2-fb796a89fb1c.png)

**Comment by blueimp** [comment]
Hi @ManjuAbhijith,

please check the HTTP logs of your web server to identify the error message.
Likely, your server is not configured to support DELETE requests.
If you cannot change that configueration, you can set the `delete_type` option of the sample PHP upload handler to `POST`:
https://github.com/blueimp/jQuery-File-Upload/blob/93467eff3721f9405758eaee3bb079f95509536b/server/php/UploadHandler.php#L58-L60

Please also see #2190
