### ISSUE TITLE
File upload-firing aws url to store the data to AWS is taking more time.

### ISSUE THREAD

**Issue by DcirrusiOS** [blueimp/jQuery-File-Upload#3691]
Hi Guys,

We are using jquery.fileupload.js version 9.22.0 for file uploading functionality which uploads the files from browser to AWS.
It is working fine, but when we try to upload more number of files, like 10,000, 30,000, 80,000., it is taking very longs time ( in hours).

When we try to debug the problem, the below function is taking more time to prepare the widgets for all the urls and then it is starting one by one.

 _onAdd: function (e, data) {
            var that = this,
                result = true,
                options = $.extend({}, this.options, data),
                files = data.files,
                filesLength = files.length,
                limit = options.limitMultiFileUploads,
                limitSize = options.limitMultiFileUploadSize,
                overhead = options.limitMultiFileUploadSizeOverhead,
                batchSize = 0,
                paramName = this._getParamName(options),
                paramNameSet,
                paramNameSlice,
                fileSet,
                i,
                j = 0;
            if (!filesLength) {
                return false;
            } else if (filesLength > 200){
				//parent.admShowconfirmmsg(mg, parent.confirm_Error, 10000, "", false, false);

			}
            if (limitSize && files[0].size === undefined) {
                limitSize = undefined;
            }
            if (!(options.singleFileUploads || limit || limitSize) ||
                    !this._isXHRUpload(options)) {
                fileSet = [files];
                paramNameSet = [paramName];
            } else if (!(options.singleFileUploads || limitSize) && limit) {
                fileSet = [];
                paramNameSet = [];
                for (i = 0; i < filesLength; i += limit) {
                    fileSet.push(files.slice(i, i + limit));
                    paramNameSlice = paramName.slice(i, i + limit);
                    if (!paramNameSlice.length) {
                        paramNameSlice = paramName;
                    }
                    paramNameSet.push(paramNameSlice);
                }
            } else if (!options.singleFileUploads && limitSize) {
                fileSet = [];
                paramNameSet = [];
                for (i = 0; i < filesLength; i = i + 1) {
                    batchSize += files[i].size + overhead;
                    if (i + 1 === filesLength ||
                            ((batchSize + files[i + 1].size + overhead) > limitSize) ||
                            (limit && i + 1 - j >= limit)) {
                        fileSet.push(files.slice(j, i + 1));
                        paramNameSlice = paramName.slice(j, i + 1);
                        if (!paramNameSlice.length) {
                            paramNameSlice = paramName;
                        }
                        paramNameSet.push(paramNameSlice);
                        j = i + 1;
                        batchSize = 0;
                    }
                }
            } else {
                paramNameSet = paramName;
            }
            data.originalFiles = files;
            $.each(fileSet || files, function (index, element) {
                var newData = $.extend({}, data);
                newData.files = fileSet ? element : [element];
                newData.paramName = paramNameSet[index];
                that._initResponseObject(newData);
                that._initProgressObject(newData);
                that._addConvenienceMethods(e, newData);
                result = that._trigger(
                    'add',
                    $.Event('add', {delegatedEvent: e}),
                    newData
                );
                return result;
            });
            return result;
        },

Particularly, the below loop is taking too long , 
            $.each(fileSet || files, function (index, element) {
                var newData = $.extend({}, data);
                newData.files = fileSet ? element : [element];
                newData.paramName = paramNameSet[index];
                that._initResponseObject(newData);
                that._initProgressObject(newData);
                that._addConvenienceMethods(e, newData);
                result = that._trigger(
                    'add',
                    $.Event('add', {delegatedEvent: e}),
                    newData
                );
                return result;
            });

Is there any way that it completes the widget of one url and starts uploading the data to AWS. Or lt completes the loop for 50 files and starts uploading to AWS like in batches.

Let me know if anymore information is required.
Kindly provide your response at the earliest.

**Comment by rosenta** [comment]
Just a question here,

I'm doing the same task, I'm just curious to know, how did you pass bucket name information to the backend API?

**Comment by DcirrusiOS** [comment]
I am calling a separate api, which gets all the bucket urls to the fileupload.js and then it directly uploads the data from browser to aws.

**Comment by blueimp** [comment]
Thanks for your report @DcirrusiOS.

By default, each file is uploaded in a separate request, which you probably want to avoid with a set of multiple thousand files.
You probably wanna look into the following two options:
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#singlefileuploads
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#limitmultifileuploads

**Comment by blueimp** [comment]
Closing this as solved.
