### ISSUE TITLE
Change Upload Folder and rename 

### ISSUE THREAD

**Issue by ebbiB** [blueimp/jQuery-File-Upload#3692]
Can you help me - where can I change the upload folder in the form (not in js). I find it in the demo.js, but i need it to change the folder dynamic . And the second question - is it possible to rename the files after or during the upload like  "001.jp; 002.jp" many thanks - Andreas

**Comment by blueimp** [comment]
If you're making use of the example PHP upload handler, you can change the upload directory with the `upload_dir` option:
https://github.com/blueimp/jQuery-File-Upload/blob/1363486f8855d6ca9c28be53a93f27e1d9db8338/server/php/UploadHandler.php#L52

Please also see #2190
