### ISSUE TITLE
cursor: pointer  not showing properly in latest chrome & firefox

### ISSUE THREAD

**Issue by deckberg-quantumdigital** [blueimp/jQuery-File-Upload#3695]
Even on your demo page it is not showing the pointer reliably between browsers.  https://blueimp.github.io/jQuery-File-Upload/

I'm going to do display: none on the file input and add a click handler and cursor: pointer to the parent to fix in the meantime.

**Comment by Rikijs** [comment]
Got cursor/pointer problems and made some tests

[1]
-- on `Windows 10` with `Chrome`, `Opera`, `Edge` - works as expected.
-- on `Windows 10` with `Firefox` - works, but cursor shows only on buttons outer border 1px!
[2]
-- on `Ubuntu Linux 2020.04` with `Chrome` - works as expected.
-- on `Ubuntu Linux 2020.04` with `Firefox` - works, but cursor shows only on buttons outer border 1px!
[3]
-- on VitrualBox `macOS 10.14` with `Chrome`, `Safari` - works as expected
-- on VitrualBox `macOS 10.14` with `Firefox` - works, but cursor shows only on buttons outer border 1px!

So from my testing, it seams, Firefox on all platforms is at fault.
Tested with current (as a time of writing) brower versions!
Tested the official demo (https://blueimp.github.io/jQuery-File-Upload/).

**Comment by Rikijs** [comment]
@deckberg-quantumdigital Does your workaround bypases current misbehaviour in Firefox?

**Comment by deckberg-quantumdigital** [comment]
Yes.  I'm guessing the current implementation was designed to downgrade gracefully if javascript is disabled but our website is so javascript heavy that we'd rather have the cursor: pointer show properly cross browser than for it to work without javascript.

On your demo page just do this:

input[type="file"] {display: none;}

and pull the input up 1 level in the DOM so it is a sibling of the span.fileinput-button

and add a click event on that span something like this:
$('span.fileinput-button').on('click', function(e){
    e.preventDefault();
    e.stopPropagation();
    $(this).parent().find('input[type="file"]').trigger('click');
    return false;
});

**Comment by blueimp** [comment]
Thanks for your report, but for the sake of backwards-compatibility I'll leave the styles as is for now.
