### ISSUE TITLE
Cancel button appear when server uploader doesn't respond with uploaded file deleteUrl

### ISSUE THREAD

**Issue by ros86** [blueimp/jQuery-File-Upload#3698]
A server uploader can deny GET and DELETE of uploaded files. The response can be:
```json
{"files": [
  {
    "name": "picture1.jpg",
    "size": 902604
  },
  {
    "name": "picture2.jpg",
    "size": 841946
  }
]}
```

but without `file.deleteUrl` `index.html` show the cancel button:
https://github.com/blueimp/jQuery-File-Upload/blob/1363486f8855d6ca9c28be53a93f27e1d9db8338/index.html#L303-L314

Could this be a good solution?
https://github.com/blueimp/jQuery-File-Upload/blob/1363486f8855d6ca9c28be53a93f27e1d9db8338/index.html#L309
`                  {% } else if (file.error) { %}`

#2538

**Comment by ros86** [comment]
any feedback?

**Comment by blueimp** [comment]
Sorry I'm not sure I understand the request.
I'll close this for now as it doesn't seem to be an issue with the library, but feel free to post further comments on this ticket.
