### ISSUE TITLE
dropzone not working in chrome but works in IE

### ISSUE THREAD

**Issue by mukeshhope** [blueimp/jQuery-File-Upload#3701]
HI Team,

I have used this plugin to upload multiple files. this code works in IE but not in chrome.
here is my code.

`$("#fileupload").fileupload({
             sequentialUploads: true,
             maxNumberOfFiles: 50,
             progress: function (e, data) {
                    console.log("data.loaded");
             },
             autoUpload: true,
             dropZone: $("#dropzone")

         });
         $("#fileupload").bind("fileuploaddrop", function (e, data) {
            console.log(data.files);
             $.each(data.files, function (index, file) {
                 //code
             });
         }).bind("fileuploadchange", function (e, data) {
             $.each(data.files, function (index, file) {
                //code
             });
         });
         // handle drag events
         $(document).bind('dragover', function (e) {
             var dropZone = $('#dropzone'),
                 timeout = window.dropZoneTimeout;
             if (timeout) {
                 clearTimeout(timeout);
             } else {
                 dropZone.addClass('in');
             }
             var hoveredDropZone = $(e.target).closest(dropZone);
             dropZone.toggleClass('hover', hoveredDropZone.length);
             window.dropZoneTimeout = setTimeout(function () {
                 window.dropZoneTimeout = null;
                 dropZone.removeClass('in hover');
             }, 100);
         });
`

this works perfectly fine in IE.
In chrome file upload works when i use file upload button to select files to upload.
But when i drag files to dropzone then in fileuploaddrop event handler data.files is a single file object no matter how many files i select. 
Please let me know if someone can help

**Comment by blueimp** [comment]
Please see #2190
