### ISSUE TITLE
Idea : Copy / Paste image

### ISSUE THREAD

**Issue by not82** [blueimp/jQuery-File-Upload#3705]
Hi, 

I didn't find a feature that seams to me really interesting.
It's pasting an image ( or anything else ) from a copy / paste, like this site : https://pasteboard.co/
I use capture tools for getting screenshots, and it would be a real shortcut to save the time of storing it, naming it, then uploading.

Thx.

**Comment by blueimp** [comment]
Hi, this is actually already supported:
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#pastezone

You can enable it on the demo by running the following command in the browser developer tools console:
```js
$('#fileupload').fileupload('option', 'pasteZone', document.body)
```
