### ISSUE TITLE
template engine not working with "add callback" 

### ISSUE THREAD

**Issue by snake-venom-nk** [blueimp/jQuery-File-Upload#3707]
my file uploader required no "form" tag because the form in which I am integrating this uploader that forms already has a form tag.
that's why I selected the "add callback".
the main demo https://blueimp.github.io/jQuery-File-Upload/ is perfect working with the the "Form" tag but if I am removing the "form" tag and submitting the uploader with "add callback"  then the the template engine not working, 
Here is my sample fiddle http://jsfiddle.net/yj5rheun/

**Comment by blueimp** [comment]
Please see #2190
