### ISSUE TITLE
Multiple file upload issue

### ISSUE THREAD

**Issue by erkanrua** [blueimp/jQuery-File-Upload#3710]
When user upload multiple files, it gives just one file showed but in XHR all files uploaded succesfull.

**Comment by ros86** [comment]
@erkanrua I think something is wrong on your backend handler response and/or on frontend x-tmpl script

**Comment by erkanrua** [comment]
Client upload speed is more than 5-10 mbps it seems. For example 5 file upload done but frontend showing just one image

**Comment by ros86** [comment]
@erkanrua  have you seen this?
https://github.com/blueimp/jQuery-File-Upload/wiki/Options#maxchunksize

Note: If this option is enabled and singleFileUploads is set to false, only the first file of a selection will be uploaded.

**Comment by lord88d** [comment]
> @erkanrua I think something is wrong on your backend handler response and/or on frontend x-tmpl script

**Comment by blueimp** [comment]
Please see #2190
