### ISSUE TITLE
"Empty file upload result" error with ASP.Net Core 3.1

### ISSUE THREAD

**Issue by NN89** [blueimp/jQuery-File-Upload#3711]
I'm using the version 9.12.3 of the plugin which is available in Nuget Package Manager. The code that was working fine with .Net Core 2.2 fails to work as expected after the code was upgraded to .Net Core 3.1 and now throws an '"Empty file upload result" error. 

I am using the basic implementation of the upload and this is the call. The url in the code is reached but it's the UI component that seems to fail and throw an error.

$('#fileupload').fileupload({
        url: url,
        acceptFileTypes: /(jpg)|(jpeg)|(png)|(gif)|(svg)$/i,
        maxFileSize: 1048576,
        maxNumberOfFiles: 1
})
    
There is a similar issue posted in Stackoverflow. ( https://stackoverflow.com/questions/63792052/blueimp-jquery-file-upload-not-compatible-with-asp-net-core-3-1 )

**Comment by blueimp** [comment]
Please see #2190 (also please note that neither the Nuget package nor any .NET solution is part of the official project).
