### ISSUE TITLE
Browse File button not working after upgrading to Bootstrap 4.6 for blueimp jQuery-File-Upload

### ISSUE THREAD

**Issue by PingPongSet** [blueimp/jQuery-File-Upload#3716]
Browse File button was working when Bootstrap v3.3.7 is used.

Howerver, after upgrading to Bootstrap 4.6, Browse File button is no longer working, not opening, and no error message shown on developer window.

**Comment by tareq2** [comment]
In bootstrap 4 the files are not showing after selecting  and i have fix it by removing the **fade** class from the template .

` <tr class="template-download fade">`

**Comment by bryanrscott** [comment]
@tareq2 might also try this from #3662 

$('#fileupload').fileupload({
  showElementClass: 'show'
});

**Comment by blueimp** [comment]
Please see #https://github.com/blueimp/jQuery-File-Upload/wiki/Style-Guide#bootstrap-ui
