### ISSUE TITLE
File Uploading Issue || If Started before Preview

### ISSUE THREAD

**Issue by deepak727** [blueimp/jQuery-File-Upload#3720]
Hello,

I am having issue while multiple file upload is on place, when I select multiple files and click on start upload button before all file thumbnails are generated, the uploader will not upload the files on which thumbs are not generated.

e.g. If I have selected 100 files and when I click on start upload button, and by that  time only 50 thumbnails are generated then uploader will only upload those 50 files rest files will not get uploaded.

Doen anyone else face this issue, Is there any workaround for this?

**Comment by blueimp** [comment]
Hi @deepak727, that is expected behavior, since the uploader only allows uploading of files that have passed the processing queue, as it might affect upload validation.
