### ISSUE TITLE
I'm getting a error it's work's fine xampp server but not on online server

### ISSUE THREAD

**Issue by himanshu01052003** [blueimp/jQuery-File-Upload#3738]
I have visited many article about this but didn't get a clue on this searching the whole internet from 1 week. I'm using blueimp to upload files.it's work's fine on xampp server but not on online server that's why I'm very confused I have not made many changes in plugin only in index.php and some change in UploadHandler.php else every thing is same it is showing the old photo's from files folder creating no new folder here is code of index.php

require('UploadHandler.php');
define("HTTP_SERVER", "/main");
session_start();
$userid = $_SESSION['uni'];

$options = array('upload_dir' =>'files'.$userid.'/', 'upload_url'=> HTTP_SERVER . "/server/php/" . 'files'.$userid.'/');
$upload_handler = new UploadHandler($options);
Here is my uploadhandler.php changes

class UploadHandler
{
//added the $options here
    protected $options;

    protected $error_messages = array(
        1 => 'The uploaded file exceeds the upload_max_filesize directive in php.ini',
        2 => 'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form',
        3 => 'The uploaded file was only partially uploaded',
to view the whole plugin visit :https://github.com/blueimp/jQuery-File-Upload

Any help or suggestion will be appreciated.Thanks in advance if any one see's reply's this.

**Comment by blueimp** [comment]
Please see #2190
