### ISSUE TITLE
Error: Cannot find module 'jquery-ui/ui/widget'

### ISSUE THREAD

**Issue by barriault** [blueimp/jQuery-File-Upload#3739]
I'm trying to implement this in a Rails 6 app with Webpacker. I'm getting the following error in my web console:

`Error: Cannot find module 'jquery-ui/ui/widget'`

I have these lines in my javascript/packs/application.js file:
```
require('blueimp-file-upload');
$(document).on('ready turbolinks:load', function() {
  $('#new_photograph').fileupload();
});
```
Any suggestions?

**Comment by decanet** [comment]
Hi, you can fix it with adding jquery-ui package (npm i jquery-ui or yarn add jquery-ui).
Also, you'll need to add require('jquery-ui'); before your require('blueimp-file-upload');

**Comment by barriault** [comment]
The necessary UI widget is supposed to already be included in this plugin. I shouldn’t have to load the full jquery UI library.

**Comment by decanet** [comment]
I agree, but I've the same error without adding myself Jquery UI.

**Comment by barriault** [comment]
Well, adding the full jQuery UI isn't fixing the problem, it's only masking the symptom. I'm looking to resolve the underlying problem. This plugin is working fine on my app with the asset pipeline, but I'm unable to upgrade to webpacker because of this issue, and since I'm using this on one page in my entire app I don't feel the proper fix is to add the entire jQuery UI.

**Comment by blueimp** [comment]
Please see #2190
