### ISSUE TITLE
File size limitation not work on IOS

### ISSUE THREAD

**Issue by YswNG** [blueimp/jQuery-File-Upload#3744]
Hi , 

I met a issue , I set **maxFileSize** to limit file size, it works when I use Chrome on PC , but it does not work when I use my phone to visit web site, I do not know why , is it a issue ? or could you tell me how to handle this ?

thanks

**Comment by YswNG** [comment]
oh,  I forgot that I also use Chrome on my phone

**Comment by blueimp** [comment]
Hi @YswNG, if you set it via https://github.com/blueimp/jQuery-File-Upload/wiki/Options#maxfilesize option, it should work as expected, including on iOS.
There is even a unit test for it: https://github.com/blueimp/jQuery-File-Upload/blob/ea641dd81c65b21af5f70a0415cfab5e51a97c49/test/unit.js#L927-L944

(side note: Chrome on iOS is just Safari with a different UI)

**Comment by blueimp** [comment]
Closing this for now, please post further information if you can provide a reproducible test case.
