### ISSUE TITLE
Validation about maxNumberOfFiles bug

### ISSUE THREAD

**Issue by liyihao2017** [blueimp/jQuery-File-Upload#3745]
Hi,

I set maxNumberOfFiles  is 10, and autoUpload is true.

When upload multiple files **simultaneously** such as 11 files, the 11th file uploaded successfully.

Validation maxNumberOfFiles  does not work.

**Comment by blueimp** [comment]
Hi @liyihao2017 

> The maxNumberOfFiles option depends on the getNumberOfFiles option.

https://github.com/blueimp/jQuery-File-Upload/wiki/Options#maxnumberoffiles
