### ISSUE TITLE
Basic Plugin and Queues

### ISSUE THREAD

**Issue by sjdean** [blueimp/jQuery-File-Upload#3746]
I love the UI that you have, but we have a use case to heavily customise the interface and provide something totally custom, while retaining the facility to show a list of files selected by the user, with a button to trigger the final upload.

Utilising the Basic Plugin, seems to auto trigger the upload, and we don't seem to be able to disable it through .fileupload({autoUpload: false});

Will we need to use the full plugin then heavily modify all the front end HTML according to our requirements? Or should this be achievable through the basic plugin?

**Comment by blueimp** [comment]
Hi @sjdean, it's certainly possible with the basic plugin:
https://github.com/blueimp/jQuery-File-Upload/wiki/Basic-plugin#how-to-start-uploads-with-a-button-click
