### ISSUE TITLE
Preview with error for some images

### ISSUE THREAD

**Issue by monoraulg** [blueimp/jQuery-File-Upload#3750]
Hello, preview with error for some images, but the error is not displayed, the preloading remains rotating. It is not a file type or size error. Any idea?

**Comment by monoraulg** [comment]
I finally found the problem. I had to update the dependency [load-image.all.min](https://raw.githubusercontent.com/blueimp/JavaScript-Load-Image/v4.0.1/js/load-image.all.min.js) and now it works correctly!

This post talks about: https://github.com/blueimp/jQuery-File-Upload/issues/3639

**Comment by blueimp** [comment]
Thanks for following up with the solution, sounds we can close this. :)
